rero/sonar

- sonar/config.py
- sonar/modules/documents/static/templates/documents/search_ui/results.html
- sonar/modules/documents/views.py
- sonar/theme/assets/js/config.js
- sonar/theme/assets/js/search_ui.js
- sonar/theme/assets/scss/sonar/theme.scss
- sonar/theme/assets/scss/usi/_variables.scss
- sonar/theme/assets/scss/usi/theme.scss
- sonar/theme/templates/sonar/frontpage.html
- sonar/theme/templates/sonar/partial/navbar.html
- sonar/theme/templates/sonar/search.html
- sonar/theme/webpack.py
* NEW Change layout in IR context
> theming: IR specific view

- sonar/config.py
- sonar/modules/documents/dojson/contrib/marc21tojson/model.py
- sonar/modules/documents/mappings/v6/documents/document-v1.0.0.json
- sonar/modules/documents/static/templates/documents/search_ui/facets.html
- sonar/theme/templates/sonar/partial/navbar.html
- sonar/theme/templates/sonar/search.html
- sonar/translations/fr/LC_MESSAGES/messages.po
- sonar/translations/messages.pot
- tests/ui/documents/test_marc21tojson.py
NEW Add facets to filter records.
> search: Faceted filters

- Dockerfile
- sonar/theme/templates/sonar/frontpage.html
- sonar/translations/de/LC_MESSAGES/messages.po
- sonar/translations/messages.pot
- tests/e2e/test_front_page.py
BETTER Add translations support for french and german.
> translations: Translations in french and german

- Pipfile
- Pipfile.lock
- run-tests.sh
- sonar/config.py
- sonar/modules/oauth/__init__.py
- sonar/modules/oauth/orcid.py
- sonar/theme/templates/sonar/accounts/login.html
- sonar/theme/templates/sonar/accounts/signup.html
- sonar/theme/templates/sonar/oauth/signup.html
- sonar/theme/templates/sonar/page.html
- sonar/theme/templates/sonar/partial/navbar.html
- sonar/translations/de/LC_MESSAGES/messages.po
- sonar/translations/fr/LC_MESSAGES/messages.po
- sonar/translations/it/LC_MESSAGES/messages.po
- sonar/translations/messages.pot
- tests/ui/oauth/conftest.py
- tests/ui/oauth/test_oauth_orcid.py
NEW OAuth authentication with ORCID api.
> authentication: ORCID OAuth

- sonar/config.py
- sonar/modules/config.py
- sonar/modules/documents/dojson/contrib/marc21tojson/model.py
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0.json
- sonar/modules/documents/mappings/v6/documents/document-v1.0.0.json
- sonar/modules/documents/marshmallow/json.py
- sonar/modules/documents/static/templates/documents/search_ui/results.html
- sonar/modules/documents/templates/documents/record.html
- sonar/modules/documents/views.py
- sonar/theme/templates/sonar/macros/macro.html
- sonar/translations/de/LC_MESSAGES/messages.po
- sonar/translations/fr/LC_MESSAGES/messages.po
- sonar/translations/it/LC_MESSAGES/messages.po
- sonar/translations/messages.pot
- tests/api/test_api_simple_flow.py
- tests/ui/documents/test_documents_views.py
- tests/ui/documents/test_marc21tojson.py
NEW Format and show information on document detail page.
BETTER Add black support for code formatting
>  templating: Document detail

- MANIFEST.in
- data/users.json
- scripts/setup
- setup.py
- sonar/config.py
- sonar/modules/api.py
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0.json
- sonar/modules/users/__init__.py
- sonar/modules/users/api.py
- sonar/modules/users/cli.py
- sonar/modules/users/jsonschemas/__init__.py
- sonar/modules/users/jsonschemas/users/user-v1.0.0.json
- sonar/modules/users/loaders/__init__.py
- sonar/modules/users/mappings/__init__.py
- sonar/modules/users/mappings/v6/__init__.py
- sonar/modules/users/mappings/v6/users/user-v1.0.0.json
- sonar/modules/users/marshmallow/__init__.py
- sonar/modules/users/marshmallow/json.py
- sonar/modules/users/serializers/__init__.py
- tests/ui/test_api.py
- tests/ui/users/data/valid.json
- tests/ui/users/data/without_email.json
- tests/ui/users/data/without_roles.json
- tests/ui/users/test_users_cli.py
* NEW Add user resource.
* NEW Link institution to user resource.
* NEW Link user account to user resource with account ID.
> record: User resource creation

- Pipfile
- Pipfile.lock
- scripts/setup
- setup.py
- sonar/config.py
- sonar/modules/deposits/__init__.py
- sonar/modules/deposits/cli.py
- sonar/modules/permissions.py
- tests/ui/test_permissions.py
* Upgrades Invenio to version 3.2 (alpha 9).
* Configures Invenio files REST.
* Creates default location for storing files.
* Closes #81
> files: configure Invenio files REST

- Pipfile
- Pipfile.lock
- sonar/modules/deposits/api.py
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0.json
- sonar/modules/deposits/rest.py
- sonar/modules/pdf_extractor/utils.py
- tests/ui/pdf_extractor/data/extracted_data.json
- tests/ui/pdf_extractor/test_pdf_extractor_utils.py
* Extracts metadata from PDF using GROBID and stores them into metadata of the file.
* Changes property types for journal data.
* Installs pycountry.
* Closes #87.
> deposit: extract metadata from PDF

- docker/nginx/nginx.conf
* Avoids log OPTIONS requests in access logs.
> nginx: remove OPTIONS requests from logs.

- sonar/modules/documents/dojson/contrib/marc21tojson/model.py
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/mappings/v6/documents/document-v1.0.0.json
- sonar/modules/documents/templates/documents/record.html
- tests/ui/documents/test_marc21tojson.py
* Removes unncessary properties from JSON schema and elasticsearch mapping.
> documents: remove unnecessary properties

- setup.py
- sonar/modules/deposits/api.py
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0.json
- sonar/modules/deposits/rest.py
- sonar/modules/documents/jsonresolvers.py
- tests/api/conftest.py
- tests/api/deposits/test_deposits_rest.py
- tests/conftest.py
- tests/ui/deposits/test_deposits_api.py
- tests/ui/test_api.py
* Creates a document when a deposit is validated.
* Refactors tests fixtures.
* Closes #114.
> deposit: Create document

- sonar/modules/api.py
- sonar/modules/documents/config.py
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/templates/documents/record.html
- sonar/modules/documents/views.py
- sonar/theme/templates/sonar/macros/macro.html
- tests/ui/documents/test_documents_views.py
* Points files to external URLs for NL documents.
* Moves modal html to display it when no additional files are not available.
* Adds margin bottom to additional files.
> documents: external URLs

- Dockerfile.base
* Adds ImageMagick in dependencies for deployment to clusters.
> deployment: install ImageMagick

- sonar/config.py
- sonar/modules/documents/dojson/contrib/marc21tojson/model.py
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/mappings/v6/documents/document-v1.0.0.json
- sonar/modules/documents/templates/documents/record.html
- tests/ui/documents/test_marc21tojson.py
* Extracts and imports collections from field 982 and store them in a "specificCollections" property.
* Shows facets for collections.
* Displays collections in detailed view.
> documents: import specific collections

- sonar/modules/documents/dojson/contrib/marc21tojson/model.py
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/mappings/v6/documents/document-v1.0.0.json
- sonar/modules/documents/templates/documents/record.html
- sonar/modules/documents/views.py
- tests/conftest.py
- tests/ui/documents/test_documents_views.py
- tests/ui/documents/test_marc21tojson.py
* Updates subjects property in JSON schema and elasticsearch mapping.
* Updates dojson transformation for subjects.
* Updates subjects display in document detail view.
> documents: update subjects

- sonar/modules/documents/dojson/contrib/marc21tojson/model.py
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- tests/ui/documents/test_marc21tojson.py
* Imports "identifiedBy" properties by following the edicted rules.
> documents: import "identifiedBy" properties

- .gitignore
- Pipfile
- Pipfile.lock
- sonar/theme/templates/sonar/accounts/login.html
- sonar/theme/templates/sonar/footer.html
- sonar/theme/templates/sonar/frontpage.html
- sonar/theme/templates/sonar/partial/switch_aai_dropdown.html
- sonar/translations/de/LC_MESSAGES/messages.po
- sonar/translations/en/LC_MESSAGES/messages.po
- sonar/translations/fr/LC_MESSAGES/messages.po
- sonar/translations/it/LC_MESSAGES/messages.po
- sonar/translations/messages.pot
* Changes "Sign-up" label for "Sign-in" for Switch AAI authentication in login page.
* Removes link to advanced search, which is not yet implemented.
* Groups "About" and "Contact" links and points to sonar.ch website.
* Ignores Visual Studio Code workspace file in Git.
* Removes the commented display of languages in footer.
* Forces sqlalchemy to version 1.3.15, because the newest version causes errors on entry points initialization.
* Closes #185.
> project: prepare for publishing TEST website

- .travis.yml
- Pipfile
- Pipfile.lock
- run-tests.sh
* Installs and uses "safety" package to temporarly check packages vulnerabilities.
* Upgrades "bleach" to version 3.1.4 for security reason.
> security: replace pipenv check by safety.

- sonar/modules/documents/api.py
* Fixes an error on clusters by changing path to affiliations file.
> documents: fix affiliations file path

- sonar/config.py
- sonar/modules/api.py
- sonar/modules/deposits/api.py
- sonar/modules/documents/api.py
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/marshmallow/json.py
- sonar/modules/documents/serializers/__init__.py
- sonar/modules/organisations/api.py
- sonar/modules/organisations/marshmallow/json.py
- sonar/modules/organisations/serializers/__init__.py
- sonar/modules/serializers.py
- sonar/modules/users/api.py
- sonar/modules/users/marshmallow/json.py
- sonar/modules/users/serializers/__init__.py
- sonar/theme/api_views.py
- tests/api/deposits/test_deposits_rest.py
- tests/api/test_api_simple_flow.py
- tests/ui/test_api_views.py
* Creates a custom JSON serializer for replacing refs if a request parameter "resolve" is available and equal to 1.
* Resets JSONSCHEMAS_RESOLVE_SCHEMA configuration to default.
* Resets JSONSCHEMAS_REPLACE_REFS configuration to default.
* Stores full schema path in "schema" property in records classes.
* Fixes path to schema in document JSON schema.
* Guesses $schema property during deserialization in marshmallow.
* Removes automatic replace refs in JSON serializer.
* Removes useless prepare_jsonschema function.
* Uses url_for function instead of hardcoding urls in tests.
> records: improve serializer

- sonar/modules/users/jsonschemas/users/user-v1.0.0.json
- sonar/modules/users/marshmallow/json.py
* Configures JSON schema for improving user editor.
* Updates fields in marshmallow for serialization and loading.
* Closes rero/sonar-ui#65.
1. Login as an administrator.
2. Go to Admin -> Records -> Users.
3. Click *Add* button.
4. Fill the form and check field requirements and validations.
5. Save user.
6. Edit user and change some fields.
7. Save user.
8. Delete user.
!!! Warning, when adding a user, there's sometimes an error because the redirection is too fast. This must be corrected in ng-core https://github.com/rero/ng-core/issues/179. Simply refresh the page to view created user details.
> user: improve editor

- data/organisations.json
- data/users.json
- scripts/setup
- sonar/modules/cli.py
- sonar/modules/organisations/cli/organisations.py
- sonar/modules/users/jsonschemas/users/user-v1.0.0.json
- tests/conftest.py
- tests/ui/organisations/cli/test_organisations_cli_organisations.py
- tests/ui/organisations/data/valid.json
- tests/ui/users/data/valid.json
- tests/ui/users/data/without_email.json
- tests/ui/users/data/without_roles.json
- tests/ui/users/test_user_jsonresolvers.py
- tests/ui/users/test_users_api.py
- tests/ui/users/test_users_cli.py
* Creates a default organisation during setup.
* Associates default organisation to users.
* Adds a CLI command for creating organisations from file.
* Sets organisation as required in user JSON schema.
> organisation: create default organisation

- sonar/common/jsonschemas/classification-v1.0.0.json
- sonar/common/jsonschemas/type-v1.0.0.json
- sonar/config.py
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/marshmallow/json.py
- sonar/modules/documents/views.py
- sonar/theme/views.py
- sonar/translations/de/LC_MESSAGES/messages.po
- sonar/translations/en/LC_MESSAGES/messages.po
- sonar/translations/fr/LC_MESSAGES/messages.po
- sonar/translations/it/LC_MESSAGES/messages.po
- sonar/translations/messages.pot
- tests/api/documents/test_documents_rest.py
- tests/api/test_api_simple_flow.py
- tests/conftest.py
documents: improve editor
* Configures JSON schema for improving document editor.
* Adds constraints and validations for certain fields.
* Adds translations for bibframe types.
* Adds a schema for files in marshmallow.
* Renames from "restricted" to "restriction" the object giving the restriction information of a file.
* Removes "restriction" object when a file is loaded in marshmallow.
* Fixes issue on file restriction when organisation is not resolved.
* Completes document types items list.
* Hierarchize form options based on a `level` property.
* Re-organize items for Classification field.
* Closes rero/sonar-ui#63.
**How to test**
1. Login as an administrator.
2. Go to Admin -> Records -> Documents.
3. Click Add button.
4. …
> documents: improve editor

- sonar/config.py
- sonar/modules/api.py
- sonar/modules/ext.py
- sonar/modules/users/api.py
- sonar/modules/users/cli.py
- sonar/modules/users/jsonschemas/users/user-v1.0.0.json
- sonar/modules/users/mappings/v6/users/user-v1.0.0.json
- sonar/modules/users/marshmallow/json.py
- sonar/templates/security/email/reset_instructions.html
- sonar/templates/security/email/reset_instructions.txt
- sonar/translations/de/LC_MESSAGES/messages.po
- sonar/translations/en/LC_MESSAGES/messages.po
- sonar/translations/fr/LC_MESSAGES/messages.po
- sonar/translations/it/LC_MESSAGES/messages.po
- sonar/translations/messages.pot
- tests/conftest.py
- tests/ui/users/test_user_jsonresolvers.py
- tests/ui/users/test_users_api.py
* Creates an account when a user record is created with a new email address.
* Synchronizes roles when a user record is updated.
* Removes account roles when a user is deleted.
* Adds a "user" cached property for storing account in user record.
* Configures the record class for user REST item route.
* Adds a method to retrieve persistent identifier object from a record.
* Adds a custom method for deleting a record in record base class (SonarRecord).
* Adds a fixture for creating roles in tests.
1. Login as superuser and go to admin and create a new user with an existing email address (user rero.sonar+[xxxx]@gmail.com.
2. Click the link in the received email to reset the password.
3. Change the password and verify that user is …
> user: synchronize user records and security accounts

- Pipfile
- Pipfile.lock
* Adds `Bootstrap-Flask` dependency explicitly in Pipfile to avoid error in Travis checks.
* Fixes version of `wand` library to 0.5.x to avoid a segmentation fault when loading images.
> project: update dependencies

- sonar/config.py
- sonar/modules/oauth/orcid.py
* Checks an environment variable for setting ORCID API domain.
* Checks ORDCID API domain to do calls on API in sandbox mode or not.
* Closes #103.
> authentication: ORCID for production

- sonar/modules/deposits/api.py
- tests/ui/deposits/test_deposits_api.py
* Adds the organisation of the logged user when a deposit is converted to document.
1. Login as administrator or moderator.
2. Create and validate a new deposit.
3. Check the document is created after deposit validation and is associated to the user organisation.
> deposits: add organisation in documents

- sonar/modules/users/jsonschemas/users/user-v1.0.0.json
* Limits users to only one role.
* Closes #241.
1. Login as admin
2. Go to Users / Add.
3. Try to select multiple roles --> Form cannot be saved.
> users: limit to only one role

- sonar/config.py
- sonar/modules/documents/dojson/rerodoc/overdo.py
- sonar/modules/documents/templates/documents/record.html
- sonar/modules/documents/views.py
- sonar/modules/ext.py
- sonar/modules/organisations/jsonschemas/organisations/organisation-v1.0.0.json
- sonar/modules/organisations/mappings/v6/organisations/organisation-v1.0.0.json
- sonar/modules/organisations/marshmallow/json.py
- sonar/modules/utils.py
- sonar/theme/assets/scss/common/_theme.scss
- sonar/theme/assets/scss/common/_variables.scss
- sonar/theme/templates/sonar/frontpage.html
- sonar/theme/templates/sonar/page.html
- sonar/theme/templates/sonar/partial/navbar.html
- sonar/translations/de/LC_MESSAGES/messages.po
- sonar/translations/en/LC_MESSAGES/messages.po
- sonar/translations/fr/LC_MESSAGES/messages.po
- sonar/translations/it/LC_MESSAGES/messages.po
- sonar/translations/messages.pot
- tests/conftest.py
- tests/ui/documents/test_documents_views.py
- tests/ui/test_utils.py
* Adds a property `isShared` in organisation to allow access to records by a specific URL.
* Adds a property `isDedicated` in organisation to allow organisation to have a specific theme and logo.
* Adds a specific route to document details instead of built-in invenio view.
* Adds a method to get current view code in templates.
* Renames `ir` query parameter to `view` for consistency.
* Stores current organisation record in Flask globals.
* Adds a header containing current organisation information in templates.
* Checks if organisation is flagged as dedicated for including custom logo and styles.
* Closes #216.
1. Try to access /organisation/unisi --> Error is thrown.
2. Login as superuser.
3. Edit unisi organisation and check …
> organisations: access records with specific URL

- sonar/config.py
- sonar/modules/ext.py
- sonar/modules/users/cli.py
- sonar/modules/users/jsonschemas/users/user-v1.0.0.json
- sonar/modules/users/signals.py
- sonar/theme/assets/scss/common/_theme.scss
- sonar/theme/templates/sonar/accounts/profile.html
- sonar/theme/templates/sonar/accounts/signup.html
- sonar/theme/templates/sonar/page_settings.html
- sonar/theme/templates/sonar/partial/dropdown_user.html
- sonar/theme/templates/sonar/partial/navbar.html
- sonar/theme/views.py
- sonar/translations/de/LC_MESSAGES/messages.po
- sonar/translations/en/LC_MESSAGES/messages.po
- sonar/translations/fr/LC_MESSAGES/messages.po
- sonar/translations/it/LC_MESSAGES/messages.po
- sonar/translations/messages.pot
- tests/ui/shibboleth_authenticator/test_shibboleth_handlers.py
- tests/ui/shibboleth_authenticator/test_shibboleth_views_client.py
- tests/ui/test_views.py
- tests/ui/users/test_users_cli.py
- tests/ui/users/test_users_signals.py
* Creates a user record when a new account is registered.
* Disables `invenio-userprofiles` module.
* Exposes and uses user record for displaying user information in templates.
* Gives role `user` by default when a new record is created.
* Removes `organisation` from required fields for users.
* Hides `applications` and `security` menu entries.
* Creates a new page for editing user data.
* Removes useless CSS rules
* Adds CSS rules for standalone editor.
* Customizes settings page.
1. Register as new user with standard registration form.
2. Login as superuser.
3. Check a user record is created with same email and roles as user account.
1. Login with Switch edu-ID account to create a new account.
2. Login as superuser.
3. Check a …
> users: create user record on registration

- data/users.json
- scripts/setup
- sonar/modules/deposits/permissions.py
- sonar/modules/deposits/query.py
- sonar/modules/ext.py
- sonar/modules/permissions.py
- sonar/modules/users/api.py
- sonar/modules/users/jsonschemas/users/user-v1.0.0.json
- sonar/theme/views.py
- sonar/translations/de/LC_MESSAGES/messages.po
- sonar/translations/en/LC_MESSAGES/messages.po
- sonar/translations/fr/LC_MESSAGES/messages.po
- sonar/translations/it/LC_MESSAGES/messages.po
- sonar/translations/messages.pot
- tests/api/deposits/test_deposits_permissions.py
- tests/api/documents/test_documents_permissions.py
- tests/api/organisations/test_organisations_permissions.py
- tests/api/users/test_users_permissions.py
- tests/conftest.py
- tests/ui/test_permissions.py
- tests/ui/test_views.py
- tests/ui/users/test_users_api.py
* Renames role `publisher` to `submitter`.
* Closes #250.
> users: rename role publisher

- sonar/modules/deposits/api.py
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/pdf_extractor/utils.py
- sonar/translations/de/LC_MESSAGES/messages.po
- sonar/translations/en/LC_MESSAGES/messages.po
- sonar/translations/fr/LC_MESSAGES/messages.po
- sonar/translations/it/LC_MESSAGES/messages.po
- sonar/translations/messages.pot
- tests/conftest.py
- tests/ui/deposits/test_deposits_api.py
- tests/ui/pdf_extractor/test_pdf_extractor_utils.py
* Adds `role` and `orcid` fields in JSON schema.
* Sets form type to `textarea` for title field.
* Adds enumeration list for agent type in documents JSON schema.
* Converts role and ORCID value when creating a document from deposit.
* Add a `creator` role when extracting contributors from PDF.
* Closes #248.
> deposits: improve form

- data/complete_document_sample.json
- sonar/modules/deposits/api.py
- sonar/modules/documents/api.py
- sonar/modules/documents/config.py
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/marshmallow/json.py
- sonar/modules/documents/templates/documents/record.html
- sonar/modules/documents/utils.py
- sonar/modules/documents/views.py
- sonar/theme/assets/scss/common/_theme.scss
- sonar/theme/templates/sonar/frontpage.html
- sonar/theme/templates/sonar/macros/macro.html
- sonar/theme/templates/sonar/manage.html
- sonar/translations/de/LC_MESSAGES/messages.po
- sonar/translations/en/LC_MESSAGES/messages.po
- sonar/translations/fr/LC_MESSAGES/messages.po
- sonar/translations/it/LC_MESSAGES/messages.po
- sonar/translations/messages.pot
- tests/api/documents/test_documents_permissions.py
- tests/conftest.py
- tests/ui/deposits/test_deposits_api.py
- tests/ui/documents/test_documents_views.py
* Improves detail views for documents.
* Removes unused macros.
* Removes unused filters functions.
* Completes JSON test document.
> documents: improve detail views

- sonar/modules/permissions.py
- tests/ui/test_permissions.py
* Restricts the access to wiki management to users having the superuser role.
> help: restrict to superuser roles.

- sonar/modules/documents/dojson/rerodoc/model.py
- sonar/modules/documents/templates/documents/record.html
- sonar/modules/documents/utils.py
- sonar/modules/utils.py
- tests/ui/documents/dojson/rerodoc/test_rerodoc_model.py
- tests/ui/documents/test_documents_utils.py
- tests/ui/test_utils.py
* Imports start date in provision activity from field `502$9`.
* Prioritizes fields for retreiving start date: 1. 260$c, 2. 269$c, 3. 773$g, 4. 502$9.
* Closes #254.
> documents: import start date from field `502$9`.

- sonar/common/jsonschemas/type-v1.0.0.json
- sonar/modules/deposits/api.py
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
- sonar/modules/documents/dojson/rerodoc/model.py
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/mappings/v6/documents/document-v1.0.0.json
- sonar/modules/documents/marshmallow/json.py
- sonar/modules/documents/templates/documents/record.html
- sonar/modules/documents/views.py
- tests/conftest.py
- tests/ui/deposits/test_deposits_api.py
- tests/ui/documents/dojson/rerodoc/test_rerodoc_model.py
- tests/ui/documents/test_documents_views.py
* Adds dissertation property in deposits JSON schema.
* Adds `grantingInstitution` and `date` properties in dissertation in documents JSON schema.
* Adds `grantingInstitution` and `date` properties in elasticsearch mapping.
* Renames `note` to `jury_note` in dissertation property.
* Populates dissertation property in document when a deposit is validated.
* Creates a filter for getting dissertation's text.
* Adds dissertation's text when document is serialized and remove it when it is loaded.
* Displays dissertation in documents detail views.
* Corrects a typo in thesis `COAR` value.
* Closes #265.
> documents: add dissertation property

- sonar/common/jsonschemas/classification-v1.0.0.json
- sonar/common/jsonschemas/language-v1.0.0.json
- sonar/common/jsonschemas/type-v1.0.0.json
For instance, document's types are hierarchically classified and for that reason, the options must not be ordered by alphabetical order. To avoid this behavior, the type of form field must be set explicitly.
* Sets form type to `enum` for `documentType` field.
* Sets form type to `enum` for `classification` field.
> editor: do not sort hierarchical options

- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/users/jsonschemas/users/user-v1.0.0.json
The date properties are now validated against a real month and a real day. Before that a date like `2020-19-19` passed the validation.
* Changes the regex for date validation in all date properties of all records types.
> records: improve date validation

- MANIFEST.in
- docker-services.yml
- docker/elasticsearch/Dockerfile
- sonar/config.py
- sonar/es_templates/v6/record.json
- sonar/modules/deposits/mappings/v6/deposits/deposit-v1.0.0.json
- sonar/modules/deposits/marshmallow/json.py
- sonar/modules/deposits/query.py
- sonar/modules/documents/mappings/v6/documents/document-v1.0.0.json
- sonar/modules/documents/marshmallow/json.py
- sonar/modules/documents/query.py
- sonar/modules/organisations/mappings/v6/organisations/organisation-v1.0.0.json
- sonar/modules/organisations/marshmallow/json.py
- sonar/modules/organisations/query.py
- sonar/modules/query.py
- sonar/modules/serializers.py
- sonar/modules/users/mappings/v6/users/user-v1.0.0.json
- sonar/modules/users/marshmallow/json.py
- sonar/modules/users/query.py
- tests/api/test_api_query.py
- tests/api/users/test_users_permissions.py
- tests/conftest.py
- tests/ui/test_query.py
For a better user experience, a serie of enhancements have been applied in this PR.
* Creates a custom docker image for elasticsearch with the ICU filter plugin.
* Improves mappings for all records types.
* Changes the way to sort records to put the best scores first.
* Changes the way to sort records to put the most recents first, when no query is specified.
* Sets a default analyzer in elasticsearch template.
* Adds a default search factory applied to all records types.
* Adds property to explain how elasticsearch set the score for a hit, if `debug` parameter is set.
* Creates a custom query parser for documents, to avoid to search in full-text by default.
* Closes #139.
> search: enhance elasticsearch mappings

- sonar/config.py
- sonar/modules/organisations/api.py
- sonar/modules/organisations/jsonschemas/organisations/organisation-v1.0.0.json
- sonar/modules/organisations/mappings/v6/organisations/organisation-v1.0.0.json
- sonar/modules/organisations/marshmallow/json.py
- sonar/theme/templates/sonar/frontpage.html
- sonar/theme/templates/sonar/page.html
- sonar/theme/templates/sonar/partial/navbar.html
- sonar/theme/templates/sonar/partial/organisation.html
- sonar/theme/views.py
- tests/conftest.py
- tests/ui/documents/dojson/rerodoc/test_rerodoc_model.py
- tests/ui/documents/dojson/rerodoc/test_rerodoc_overdo.py
- tests/ui/organisations/cli/test_organisations_cli_organisations.py
- tests/ui/test_views.py
This commit shows information about the current organisation, as the title, the description and optionally a logo. Users can search for records that belong to this organisation only.
* Enables REST endpoints for organisations files.
* Enables UI endpoints for organisations files.
* Associates un bucket when an organisation is created.
* Adds `description`, `_bucket` and `_files` properties to JSON schema.
* Adds `description` property to elasticsearch mapping.
* Serializes `description`, `_bucket` and `_files` properties when organisation is retrieved by REST API.
* Adds a Jinja filter to get an image URL for a record.
* Displays organisation's information in front page and inner pages.
* Searches only for global records in main search input.
* Closes #268.
Co-Authored-by: Sébastien …
> organisations: show organisation information

- sonar/modules/users/permissions.py
- sonar/modules/users/query.py
- tests/api/users/test_users_permissions.py
- tests/conftest.py
The admin users must be able to list users not associated to an organisation.
* Modifies the query for retrieving users to include users without organisation.
* Tests the existence of the organisation in user records to avoid an error if it not exists.
* Closes #273.
> users: list users with no organisation

- sonar/modules/deposits/api.py
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
- sonar/modules/documents/templates/documents/record.html
- tests/conftest.py
- tests/ui/deposits/test_deposits_api.py
The goal of this PR is to handle `identifiedBy` field in deposit process and create this field in document when deposit is validated.
* Adds `identifiedBy` data to document when deposit is validated.
* Adds `identifiedBy` field to deposit JSON schema so that the field is displayed in deposit form.
* Moves `hideExpression` properties into `form` object to be consistent with `ng-core` editor.
* Adds `editor-title` CSS class to main properties of deposit JSON schema.
* Displays identifiers in document detail view.
> deposits: handle `identifiedBy` field.

- sonar/config.py
- sonar/templates/security/email/welcome.html
* Customizes welcome e-mail by overriding default template from `flask-security`.
* Closes #272.
> account: customize welcome e-mail

- sonar/modules/documents/query.py
- tests/api/test_api_query.py
The search in full-text is not exclusive, it means that the search must be done in all fields and the `fulltext` field, not only in the latter.
* Updates the query to search in all fields when a full-text search is triggered.
> documents: search in full-text

- sonar/config.py
* Sets a default size with value `50` for all aggregations.
> records: set default aggregation size

- sonar/modules/documents/cli/oaiharvester.py
The second time `harvest-all` command is called, only records updated since last run are imported. With this new option, it forces to re-import all records.
* Adds a `--force` option to re-import all records.
> documents: add option to force harvesting records

- sonar/modules/api.py
- sonar/modules/documents/api.py
- sonar/modules/documents/dojson/rerodoc/model.py
- sonar/modules/ext.py
- sonar/modules/receivers.py
- tests/api/test_receivers.py
- tests/conftest.py
- tests/ui/documents/test_documents_api.py
- tests/ui/test_api.py
This commit aims to refactor the way files are handled when added to a record, to be more generalistic and have specific treatment for documents without affecting others records types.
* Moves specific methods `create_thumbnail` and `create_fulltext_file` in `DocumentRecord`
* Tests file existence to determine if file have to be processed.
* Handles files metadata in a more generalistic way.
* Connects to `file_uploaded` and `file_deleted` signals with to different functions, to know if the file is deleted when processing.
* Removes `size` property when harvesting from RERODOC, as this property is calculated when the file is created.
> records: refactor file handling

- setup.cfg
* Adds the line number and the file where translation is found when the messages are extracted.
* Closes #302.
> translations: add context when extracting messages

- sonar/translations/it/LC_MESSAGES/messages.po
Italian translated at 98.3% (896 of 911 strings)
Co-authored-by: Nicolas Prongué <n.prongue@outlook.com>
Translation: RERO+/sonar
> translations: update catalogs

- Pipfile
- Pipfile.lock
- docker-compose.full.yml
- pytest.ini
- scripts/server
- scripts/setup
Updates celery to version 5 and adapts celery server commands.
* Updates celery command in `server` script.
* Updates celery command in docker deployment file.
* Purges celery tasks in `setup` script.
* Avoids error with `invenio-previewer` by fixing `nbconvert` library to a smaller version than 6.
* Registers celery testing plugins in main `conftest.py` file.
* Closes #331.
> dependencies: update celery to version 5

- sonar/theme/templates/sonar/macros/macro.html
* Shows thumbnail if no external URL is set, even if organisation is configured to point to external files.
> documents: fix thumbnail without external URL

- sonar/modules/documents/dojson/rerodoc/model.py
- tests/ui/documents/dojson/rerodoc/test_rerodoc_model.py
If an identifier is set in field `091` (dedicated to PMID), this value is imported as a `bf:Local` identifier with a `PMID` source.
* Updates import to convert PMID identifier to local identifer with a `PMID` source.
> imports: change PMID identifier

- sonar/modules/users/signals.py
- sonar/theme/templates/sonar/page_settings.html
- sonar/theme/templates/sonar/partial/dropdown_user.html
- sonar/theme/templates/sonar/partial/navbar.html
- sonar/theme/views.py
- tests/ui/users/test_users_signals.py
This commit is a rollback of functionality done before, to avoid user resource to be created when a user registers in public interface.
* Avoids creating user resource when a user registers.
* Hides `Admin` entry from user's menu, as this entry is already available in user's dropdown.
* Shows invenio profiles entry in user's menu only if no user resource is associated to current user.
* Changes dropdown display depending if user resource exists or not.
* Closes #314.
> users: avoid create user resource

- sonar/modules/documents/api.py
- sonar/modules/documents/marshmallow/json.py
- sonar/modules/documents/templates/documents/record.html
- sonar/modules/documents/views.py
- tests/ui/documents/test_documents_api.py
- tests/ui/documents/test_documents_views.py
This commit ensures that files are ordered correctly, for having the main file at first position. The sort is based on `order` property from files.
* Adds a method to order and filter files in DocumentRecord.
* Removes useless `files_by_type` filter.
* Sorts files before dumping them in REST API.
> documents: order files

- sonar/config.py
- sonar/modules/query.py
- tests/api/users/test_users_query.py
This commit allows to show a checkbox in SONAR UI that filters users no attached to an organisation. The implementation in user interface has been done in rero/sonar-ui#142.
* Configures aggregation and filter for filtering users not attached to any organisation.
* Adds a new filter for querying records not having a specific field.
* Closes #305.
> users: facet for users without organisation

- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/mappings/v6/documents/document-v1.0.0.json
- tests/conftest.py
* Configures `_files` property in JSON schema for editing files metadata.
* Adds a date format for `embargo_date` in elasticsearch mapping.
* Closes #280.
> documents: configure `_files` in JSON schema

- Pipfile
- Pipfile.lock
* Fixes version for `importlib-metadata` to a smaller version than 2.0 to avoid an error when deploying to clusters. See https://github.com/pypa/pipenv/issues/4476 for more info.
> dependencies: fix version for `importlib-metadata`

- sonar/modules/organisations/marshmallow/json.py
- tests/api/organisations/test_organisations_permissions.py
This PR checks if current user can activate the `shared` or `dedicated` mode. Only super users can do this.
* Adds a validation for `isShared` and `isDedicated` properties in marshmallow schema.
* Closes #351.
> organisations: validate modes update

- sonar/config.py
- sonar/modules/deposits/mappings/v6/deposits/deposit-v1.0.0.json
For all record types, the default behavior is to have the most recent records first, if no query is specified.
* Configures sort options and default sort for all record types.
* Adds `_created` and `_updated` fields to deposit's elasticsearch mapping.
* Closes #318.
> records: sort by most recent descending by default

- sonar/modules/documents/serializers/__init__.py
- sonar/translations/manual_translations.txt
Set the name of the organisations instead of their codes in facet before sending response in API.
* Sets the name of the organisation in corresponding facet in documents serializer.
* Removes useless manual translations for organisations.
* Closes #320.
> documents: update name in organisation facet

- sonar/modules/deposits/api.py
- sonar/modules/deposits/mappings/v6/deposits/deposit-v1.0.0.json
* Fixes date format to UTC timezone for deposit logs.
* Closes #333.
> deposit: fix log date format

- scripts/bootstrap
- sonar/config.py
- sonar/theme/assets/scss/preview.scss
- sonar/theme/templates/sonar/preview/base.html
- sonar/theme/webpack.py
This PR customizes the sidebar of the PDF previewer, to make the bookmarks more visible. It integrates some modifications to improve the PDF preview experience (i.e. with Firefox).
* Copies the worker from `pdf.js` in static folder, to avoid an error when loading the preview.
* Allows `data` and `blob` sources for fonts in content security policies.
* Adds and uses a custom base template for preview, to allow to override styles from `pdf.js`.
* Adds a custom styles sheet for previews.
* Closes #336.
> documents: Customize PDF preview styles

- sonar/modules/deposits/api.py
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
* Removes `minLength` property for contributors, as they are not required.
* Checks if `contributors` property exists when document is created from the deposit.
* Closes #352.
> deposits: contributors are not required

- setup.py
- sonar/modules/documents/marshmallow/json.py
- sonar/modules/documents/templates/documents/record.html
- sonar/modules/documents/views.py
- tests/ui/documents/test_documents_views.py
This commit displays the complete meeting information, with number, place and date.
* Creates a view filter to format contribution display.
* Adds the formatted text before serialization.
* Removes the formatted text before JSON loading.
* Displays the formatted text in record detail view.
* Registers the i18n extension in API application, to make the translations available.
* Closes #338.
> documents: meeting display

- sonar/common/jsonschemas/license-v1.0.0.json
- sonar/modules/deposits/api.py
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
- sonar/modules/deposits/mappings/v6/deposits/deposit-v1.0.0.json
- sonar/modules/documents/dojson/rerodoc/model.py
- sonar/modules/documents/dojson/rerodoc/overdo.py
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/mappings/v6/documents/document-v1.0.0.json
- sonar/modules/documents/marshmallow/json.py
- sonar/modules/documents/templates/documents/record.html
- tests/conftest.py
- tests/ui/documents/dojson/rerodoc/test_rerodoc_model.py
This PR aims to add a license to deposit and document records. Moreover, the `usageAndAccessPolicy` will be added when a record is imported from RERO DOC.
* Creates a JSON schema for license property.
* Creates the `usageAndAccessPolicy` property in documents when the document is created from a deposit.
* Updates the `usageAndAccessPolicy` property of documents to match the specs.
* Adds a `license` property in deposit's JSON schema.
* Updates the conversion of field `540$a` to match the new structure of the `usageAndAccessPolicy` property.
* Adds a default license for RERO DOC documents if the license is not set.
* Makes the field `usageAndAccessPolicy` available when a document is serialized.
* Displays the license in document's detail view.
* Closes #324.
Co-Authored-by: Sébastien …
> deposits: add license

- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
* Fixes hide expression for `identifiedBy` field in contributions by checking the right model.
> documents: fix contributions in editor.

- MANIFEST.in
- sonar/config.py
- sonar/modules/documents/api.py
- sonar/modules/documents/ext.py
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/mappings/v7/documents/document-v1.0.0.json
- sonar/modules/documents/marshmallow/json.py
- sonar/modules/documents/minters.py
- sonar/modules/documents/receivers.py
- sonar/modules/organisations/api.py
- sonar/theme/static/xsl/oai2.xsl
- tests/conftest.py
- tests/ui/documents/dojson/rerodoc/test_rerodoc_model.py
- tests/ui/documents/dojson/rerodoc/test_rerodoc_overdo.py
- tests/ui/documents/test_documents_receivers.py
- tests/ui/organisations/cli/test_organisations_cli_organisations.py
- tests/ui/organisations/test_organisations_oai_set.py
- tests/ui/test_api.py
* Creates an OAI set when an organisation is created.
* Configures OAI ID prefix.
* Updates JSON schema and elasticsearch mapping for documents to store the `_oai` property.
* Updates the `_oai` property of record when a document is created or updated, accordingly to his organisation.
* Serializes the `_oai` property when document is sent to API.
* Closes #311.
> documents: configure OAI sets

- poetry.lock
- pyproject.toml
- sonar/config.py
- sonar/modules/api.py
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
- sonar/modules/deposits/mappings/v7/deposits/deposit-v1.0.0.json
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/mappings/v7/documents/document-v1.0.0.json
- sonar/modules/documents/marshmallow/json.py
- sonar/modules/documents/serializers/__init__.py
- sonar/modules/documents/serializers/dc.py
- sonar/modules/documents/serializers/schemas/dc.py
- sonar/modules/documents/utils.py
- sonar/modules/documents/views.py
- sonar/modules/organisations/jsonschemas/organisations/organisation-v1.0.0.json
- tests/ui/documents/test_dc_schema.py
- tests/ui/documents/test_documents_views.py
This PR configures OAI server to export documents records in Dublin Core formats.
* Installs `dcxml` library to generate the output in Dublic CORE XML.
* Creates and configures the serializer for `oai_dc` format.
* Dumps `mimetype` from file object to record's file metadata.
* Adds a serializer schema for Dublic Core.
* Adds `mimetype` property to all resources that use files.
* Avoids to display issue and pages if volume is not defined in `partOf` property.
* Closes #325.
> documents: export records in Dublic Core format

- poetry.lock
- pyproject.toml
Fixes security issue by updating the `lxml` library to version 4.6.2 or greater.
> dependency: fix security issue

- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
Spotted by @pronguen at Weblate :) https://hosted.weblate.org/translate/rero_plus/sonar/en_US/?checksum=bbb06e89b3f66d7f#comments
> Spelling: i.e x4, -to which x2

- sonar/theme/templates/sonar/partial/navbar.html
* Displays a small `SONAR` header if we are in an organisation shared view.
* Closes #385.
> organisation: display a small header

- sonar/modules/documents/templates/documents/record.html
- sonar/theme/templates/sonar/partial/organisation.html
* Adds a button to go back to search results in documents detail views.
* Reduces the size of `Back to SONAR` button in organisation's context.
* Closes #383.
> documents: add a back button in detail views

- sonar/modules/documents/dojson/rerodoc/model.py
* Gives a default document type (coar:c_db06) for thesis which don't have `980$f` field.
* Fixes #361.
> rerodoc: default document type for thesis

- scripts/setup
Drops all tables instead of drop database to avoid errors in production cluster, as DB user has no privileges to drop or create a database.
> db: drop tables instead of drop database

- .github/workflows/continuous-integration-test.yml
Fixes an issue when GitHub actions submit to `coveralls` API. This issue appears since the new published version of `coveralls-python`.
> ci: fix coveralls issue

- babel.ini
- sonar/common/jsonschemas/type-v1.0.0.json
- sonar/modules/config.py
- sonar/modules/deposits/api.py
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
- sonar/modules/documents/templates/documents/record.html
- tests/conftest.py
- tests/ui/deposits/test_deposits_api.py
* Adds `publicationPlace` and `publisher` properties.
* Makes date mandatory and changes description, pattern, placeholder and validation message.
* Moves `language` property before `otherLanguageTitle`.
* Displays a three rows textarea for title and abstracts.
* Fixes the display of all placeholders.
* Extracts translations messages from `*Message` in JSON schemas.
* Adds some preferred choices in document type enumeration.
* Adds provision activity statements for place and agent when a document is create from a deposit.
* Displays title with carriage returns in documents detail views.
* Closes #310.
* Closes #387.
> deposit: improve editor

- docker-services.yml
- setup.py
- sonar/elasticsearch/__init__.py
- sonar/elasticsearch/cli.py
- tests/unit/elasticsearch/test_elasticsearch_cli.py
This PR provides CLI commands to backup and restore elasticsearch indices and data.
* Installs CLI commands in `setup.py`.
* Creates CLI commands for creating a repository, creating a snapshot and restoring a snapshot.
* Mount a temp path in elasticsearch docker service and add the `path.repo` configuration to make snapshot working.
> es: backup and restore

- sonar/modules/documents/tasks.py
* Avoids to log info in sentry when the document file cannot be downloaded.
> documents: avoid log in sentry

- sonar/modules/documents/templates/documents/record.html
* Adds a link for identifiers of type `DOI`.
* Closes #403.
> documents: set DOI clickable

- sonar/modules/deposits/api.py
- sonar/modules/documents/dojson/rerodoc/model.py
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/loaders/schemas/rerodoc.py
- sonar/modules/documents/marshmallow/json.py
- sonar/modules/documents/permissions.py
- sonar/modules/documents/receivers.py
- sonar/modules/documents/utils.py
- tests/api/documents/test_documents_permissions.py
- tests/conftest.py
- tests/ui/deposits/test_deposits_api.py
- tests/ui/documents/dojson/rerodoc/test_rerodoc_model.py
- tests/ui/documents/test_dc_schema.py
- tests/ui/documents/test_documents_utils.py
- tests/ui/documents/test_documents_views.py
- tests/ui/organisations/test_jsonresolvers.py
- tests/unit/documents/loaders/test_rerodoc_loader.py
* Allows to store multiple organisations for a document.
> documents: allow multiple organisations

- sonar/es_templates/v7/record.json
- sonar/modules/shibboleth_authenticator/handlers.py
- sonar/modules/users/jsonschemas/users/user-v1.0.0.json
- sonar/modules/users/mappings/v7/users/user-v1.0.0.json
- tests/ui/shibboleth_authenticator/test_shibboleth_handlers.py
* Fixes an issue when the accounts from Switch and Invenio are linked and the email address are not corresponding because of case sensivity.
* Closes #397.
> authentication: fix Switch edu-ID authentication

- scripts/test
Ignores temporarily a vulnerability in `tornado` library, because the a vulnerable version is forced in `invenio-previewer`.
> dependencies: ignore vulnerability

- sonar/theme/assets/scss/common/_theme.scss
- sonar/theme/templates/sonar/page.html
- sonar/theme/templates/sonar/page_wiki.html
* Fixes links in table of contents by adding a `base href` tag into the page.
* Closes #450.
> help: fix TOC links

- sonar/affiliations/affiliation_resolver.py
- tests/unit/affiliations/test_affiliation_resolver.py
* Increases the score for affiliation matching, to avoid the error reported in the issue.
* Fixes #465.
> documents: fix controlled affiliation matching

- sonar/heg/serializers/schemas/heg.py
- tests/unit/heg/cli/test_heg_cli_harvest.py
- tests/unit/heg/serializers/schemas/test_heg_serializers_schemas_heg.py
Fixes an error when processing records with language code `es`. As the two digit code for spanish is `sp` in config.py.
> HEG import: fix `es` language code

- sonar/heg/cli/harvest.py
- sonar/heg/ftp/__init__.py
- tests/unit/heg/cli/test_heg_cli_harvest.py
- tests/unit/heg/ftp/test_heg_repository.py
* Splits source files into smaller files of 500 records.
* Removes file after it has been processed.
> HEG import: split files

- .github/workflows/continuous-integration-test.yml
Fixes the installation fail during CI tests by explicitly specifying the package for `xpdf` library.
> ci: fix `xpdf` installation error

- Dockerfile.base
Forces upgrade `pip` before installing libraries, to avoid an error.
> docker: force upgrade pip

- sonar/theme/templates/sonar/frontpage.html
* Remove the banner indicating that the application is in development.
* Keeps the message that data can be erased, but only for non-production environments.
* Closes #107.
> frontpage: remove banner

- sonar/heg/serializers/schemas/crossref.py
- sonar/heg/serializers/schemas/medline.py
- sonar/modules/documents/templates/documents/record.html
- sonar/modules/utils.py
- tests/ui/test_utils.py
* Removes markup from abstract when importing data from HEG.
* Removes the call of `safe` filter as it is useless.
* Closes #461.
> HEG import: remove markup from abstract

- sonar/modules/documents/serializers/__init__.py
- sonar/modules/documents/serializers/google_scholar.py
- sonar/modules/documents/serializers/schemaorg.py
- sonar/modules/documents/serializers/schemas/__init__.py
- sonar/modules/documents/serializers/schemas/base_schema.py
- sonar/modules/documents/serializers/schemas/dc.py
- sonar/modules/documents/serializers/schemas/google_scholar.py
- sonar/modules/documents/serializers/schemas/schemaorg.py
- sonar/modules/documents/templates/documents/record.html
- sonar/modules/documents/views.py
- tests/unit/documents/serializers/test_google_scholar_schema.py
- tests/unit/documents/serializers/test_schemaorg_schema.py
* Adds JSON-LD data for schema.org.
* Adds citation metadata for Google Scholar.
* Adds title and meta description.
* Creates a base serializer schema and moves some functions into it.
* Creates a serializer for schema.org metadata.
* Creates a serializer for Google scholar metadata.
* Closes #98.
* Closes #99.
> documents: add metadata in detail view

- sonar/heg/record/__init__.py
- sonar/heg/serializers/schemas/unpaywall.py
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/mappings/v7/documents/document-v1.0.0.json
- sonar/modules/documents/marshmallow/json.py
- sonar/modules/documents/query.py
- sonar/modules/documents/views.py
- tests/unit/heg/record/test_heg_record.py
- tests/unit/heg/serializers/schemas/test_heg_serializers_schemas_unpaywall.py
Adds a property to hide records in public views. This is needed for example for HEG, when a record has no file attached.
* Adds the `hiddenToPublic` property to documents.
* Does not search for records having the flag activated.
* Throws a 404 in detail view when the flag is activated.
* Removes empty properties when `Unpaywall` record is serialized.
* Flags HEG record as hidden if no file is linked to it.
* Closes #464.
> documents: add `hiddenToPublic` property

- sonar/modules/deposits/marshmallow/json.py
- sonar/modules/deposits/permissions.py
- sonar/modules/documents/marshmallow/json.py
- sonar/modules/documents/permissions.py
- sonar/modules/organisations/api.py
- sonar/modules/organisations/marshmallow/json.py
- sonar/modules/organisations/permissions.py
- sonar/modules/permissions.py
- sonar/modules/projects/marshmallow/json.py
- sonar/modules/projects/permissions.py
- sonar/modules/users/api.py
- sonar/modules/users/marshmallow/json.py
- sonar/modules/users/permissions.py
- sonar/theme/views.py
- tests/ui/documents/test_documents_utils.py
- tests/ui/organisations/test_organisations_api.py
- tests/ui/users/test_users_api.py
* Avoids to check permissions if the call is done by the a public view.
* Uses user record instead of flask user in permissions.
* Avoids multiple calls when retrieving current user record.
* Avoids multiple calls when retrieving current organisation.
* Closes #245.
> permissions: improve permissions checks

- sonar/common/jsonschemas/type-v1.0.0.json
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/projects/jsonschemas/projects/project-v1.0.0_src.json
* Updates JSON schema properties after upgrading ng-core version as the behavior of the editor has changed.
* Removes `editor-title` CSS class.
* Adds `hide` property for `provisionActivity.statement`, `partOf` and `hiddenFromPublic` fields.
* Adds manually `card` wrapper to deposit fields.
> editor: update JSON schema properties

- sonar/modules/organisations/marshmallow/json.py
- sonar/theme/views.py
- tests/api/organisations/test_organisations_permissions.py
- tests/ui/test_views.py
* Fixes an error when editing the organisation with an admin role.
* Removes `isShared` and `isDedicated` fields if user does not have superuser role.
* Guesses `isShared` and `isDedicated` values from user's organisation when user does not have superuser role, during the serialization.
* Closes #492.
> organisations: fix editor with admin role

- sonar/modules/organisations/jsonschemas/organisations/organisation-v1.0.0.json
* Updates the description for the field `allowedIps`.
* Closes #495.
> organisations: update `allowedIps` description

- sonar/modules/users/api.py
- tests/ui/users/test_users_api.py
* removes Flask user when an user record is deleted.
* Closes #491.
> users: remove Flask user

- poetry.lock
- pyproject.toml
- sonar/config.py
- sonar/modules/documents/views.py
* Installs `invenio-stats` library.
* Configures the collect of stats for documents views and files views.
* Fires the `view` event in custom documents detail view.
> stats: configure stats for documents and files

- docker-services.yml
- docker/elasticsearch/Dockerfile
- docker/postgres/Dockerfile
- poetry.lock
- pyproject.toml
- pytest.ini
- sonar/config.py
- sonar/modules/documents/receivers.py
- sonar/modules/ext.py
- sonar/theme/templates/sonar/preview/base.html
- sonar/theme/webpack.py
* Upgrades Invenio library to version 3.4 and adjusts all the related dependencies.
* Upgrades PostgreSQL to version 12 in docker containers.
* Upgrades Elasticsearch to version 7.10.1 in docker containers.
* Sets an Elasticsearch config `cluster.routing.allocation.disk.threshold_enabled` to false, to avoid checks for disk space in local context.
* Removes PEP8 checks during the tests, as the plugin is not maintained anymore.
* Adds a configuration `APP_THEME` to specify the application wide theme.
* Removes useless assets registration in main extension.
* Adds `popper.js` library to webpack, because it is used in invenio-previewer.
* Refactors invenio-previewer custom base template.
* Fixes the `update_oai_property` signal receiver, to make it work with the new version of …
> project: upgrade to Invenio 3.4

- setup.py
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/users/mappings/v7/users/user-v1.0.0.json
- sonar/modules/users/marshmallow/json.py
- sonar/proxies.py
- sonar/resources/projects/mappings/v7/projects/project-v1.0.0.json
- sonar/suggestions/__init__.py
- sonar/suggestions/rest.py
- tests/api/suggestions/test_suggestions_rest.py
- tests/unit/test_sonar_proxy.py
* Adds a REST endpoint for getting suggestions completion.
* Set the type to `completion` for fields used in suggestions.
* Raises an exception if a resource is not found in SONAR proxy.
* Fixes a typo in remote typeahead in documents.
* Serializes `full_name` property in users marshmallow schema.
> search: suggestions completion API endpoint

- sonar/dedicated/hepvs/projects/jsonschemas/hepvs/projects/project-v1.0.0_src.json
- sonar/resources/projects/jsonschemas/projects/project-v1.0.0_src.json
- sonar/resources/projects/mappings/v7/projects/project-v1.0.0.json
- sonar/resources/projects/schema.py
- tests/api/suggestions/test_suggestions_rest.py
* Configures the editor for HEP Valais.
* Adds a REST endpoint for getting suggestions completion.
* Set the type to `completion` for fields used in suggestions.
* Raises an exception if a resource is not found in SONAR proxy.
* Fixes a typo in remote typeahead in documents.
* Serializes `full_name` property in users marshmallow schema.
* Closes #454.
> projects: editor for HEP Valais

- docs/conf.py
- poetry.lock
- pyproject.toml
- scripts/test
- sonar/config.py
- sonar/ext.py
- sonar/modules/documents/cli/oaiharvester.py
- sonar/modules/documents/dojson/rerodoc/model.py
- sonar/modules/documents/permissions.py
- sonar/modules/documents/templates/documents/record.html
- sonar/modules/documents/views.py
- sonar/resources/projects/views.py
- sonar/route_converters.py
- sonar/theme/templates/sonar/frontpage.html
- sonar/theme/templates/sonar/partial/navbar.html
- sonar/theme/templates/sonar/partial/organisation.html
- sonar/theme/views.py
- tests/api/users/test_users_query.py
- tests/ui/documents/cli/test_documents_cli_oaiharvester.py
- tests/ui/documents/cli/test_documents_cli_rerodoc.py
- tests/ui/documents/dojson/rerodoc/test_rerodoc_model.py
- tests/ui/documents/test_documents_views.py
- tests/ui/test_cli.py
- tests/ui/test_fetchers.py
- tests/ui/test_utils.py
- tests/ui/users/test_users_api.py
* Adds document and project detailed view in the invenio-records-ui
configuration.
* Adds permissions to the detailed, preview and file document views to
limit the access to the public documents.
* Adds front page route and the global jinja filters to the main
extension application.
* Adds a new werkzeug converter to limit the view matched routes to the
existing organisations.
* Use `autoflake` to detect unused import packages.
> view: change the view routes

- sonar/common/jsonschemas/classification-v1.0.0.json
- sonar/common/jsonschemas/language-v1.0.0.json
- sonar/common/jsonschemas/license-v1.0.0.json
- sonar/common/jsonschemas/type-v1.0.0.json
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/theme/views.py
* Configures options tree for document type.
* Configures options tree for classification.
* Disables the options hierarchization before sending schema as it is done in frontend now.
* Closes #530.
> json schemas: configure options tree for select

- sonar/modules/documents/marshmallow/json.py
- sonar/modules/documents/tasks.py
- tests/ui/documents/test_documents_tasks.py
* Flags record as `harvested` when it is imported from an external source.
* Closes #556.
> documents: flag record as `harvested`

- sonar/config.py
- sonar/heg/record/__init__.py
- sonar/heg/serializers/schemas/unpaywall.py
- sonar/modules/api.py
- sonar/modules/documents/api.py
- sonar/modules/documents/ext.py
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/mappings/v7/documents/document-v1.0.0.json
- sonar/modules/documents/marshmallow/json.py
- sonar/modules/documents/query.py
- sonar/modules/documents/receivers.py
- tests/ui/documents/test_documents_api.py
- tests/ui/documents/test_documents_receivers.py
- tests/ui/test_query.py
- tests/unit/heg/record/test_heg_record.py
- tests/unit/heg/serializers/schemas/test_heg_serializers_schemas_unpaywall.py
* Adds a filter to search only for open access documents.
* Configures `oa_status` field to display it in editor.
* Sets the `access` property of the first files when the record is imported from HEG.
* Forces files to point to external URLs for records imported from HEG.
* Fixes an error when trying to retrieve the record corresponding to the file bucket and record has an OAI PID.
* Removes the useless `hiddenFromPublic` property in documents.
* Closes #511.
> search: add filter for open access documents

- sonar/resources/params.py
- sonar/resources/projects/service.py
- sonar/resources/service.py
- tests/api/projects/test_projects_filters.py
- tests/conftest.py
This PR aims to apply filters during the search process, as `invenio_records_resources` just applies `post_filters` at this time...
* Creates a record service configuration to fill the custom `FacetsParam` class.
* Applies filters if some are defined in configuration.
* Closes #554.
> resources: apply filters

- scripts/bootstrap
* Copies the `manifest.json` to ${INVENIO_INSTANCE_PATH}/static/dist, something changed in `invenio-assets` and this file is missing.
> assets: copy manifest.json to fix webpack error

- sonar/ext.py
- sonar/heg/serializers/schemas/heg.py
- sonar/modules/collections/jsonschemas/collections/collection-v1.0.0.json
- sonar/modules/documents/views.py
- sonar/modules/utils.py
- tests/ui/documents/test_documents_views.py
- tests/ui/test_utils.py
* Adds a filter to get the value corresponding to a language in a list property.
* Moves `get_bibliographic_code_from_language` into utils functions.
> templates: add language value filter

- .gitignore
- MANIFEST.in
- scripts/bootstrap
- sonar/config.py
- sonar/json_schemas/__init__.py
- sonar/json_schemas/documents_json_schema.py
- sonar/json_schemas/factory.py
- sonar/json_schemas/json_schema_base.py
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/mappings/v7/documents/document-v1.0.0.json
- sonar/modules/documents/marshmallow/json.py
- sonar/modules/documents/query.py
- sonar/modules/documents/serializers/__init__.py
- sonar/modules/documents/templates/documents/record.html
- sonar/modules/documents/views.py
- sonar/modules/organisations/jsonschemas/organisations/organisation-v1.0.0_src.json
- sonar/modules/organisations/mappings/v7/organisations/organisation-v1.0.0.json
- sonar/modules/organisations/marshmallow/json.py
- sonar/theme/views.py
- tests/api/documents/test_documents_permissions.py
- tests/conftest.py
- tests/ui/documents/test_documents_views.py
- tests/unit/json_schemas/test_documents_json_schema.py
- tests/unit/json_schemas/test_json_schema.py
- tests/unit/json_schemas/test_json_schema_factory.py
* Adds the support of custom fields for dedicated organisations documents.
* Adds the filters and aggregations for the custom fields.
* Creates a custom class for managing JSON schemas, with a factory to instantiate the right class.
* Configures JSON schema and Elasticsearch mapping for the three custom fields.
* Adjusts facets for custom fields depending on the context (dedicated view or not).
* Displays the custom fields in documents detail view.
* Adds properties in organisation (JSON schema and mapping) to configure the behavior of the custom fields.
* Refactors the view serving the JSON schema, to use the new class and factory.
* Closes #512.
> documents: custom fields for documents

- scripts/test
Fixes temporarly safety check by ignoring the vulnerability 40459 corresponding to flask-caching.
This fix can be removed when a new release of flask-caching will correct that.
Co-Authored-by: Sébastien Délèze sebastien.deleze@rero.ch
> tests: fix temporarly safety check

- sonar/common/jsonschemas/language-v1.0.0.json
- sonar/common/jsonschemas/license-v1.0.0.json
- sonar/common/jsonschemas/oa-status-v1.0.0.json
- sonar/modules/deposits/api.py
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- tests/conftest.py
- tests/ui/deposits/test_deposits_api.py
* Improves editor and process for deposits.
* Closes #569.
* Closes #560.
> deposits: improve editor and process

- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/templates/documents/record.html
* Removes the field from the document editor.
* Fixes the display of the tooltip in document detail view.
* Forces to clear cache for JSON schemas, to have the right schema content.
* Closes #541.
> documents: fix controlled affiliations

- sonar/translations/de/LC_MESSAGES/messages.po
- sonar/translations/en/LC_MESSAGES/messages.po
- sonar/translations/eo/LC_MESSAGES/messages.po
- sonar/translations/fr/LC_MESSAGES/messages.po
- sonar/translations/it/LC_MESSAGES/messages.po
- sonar/translations/messages.pot
- sonar/translations/nb_NO/LC_MESSAGES/messages.po
German translated at 88.1% (979 of 1111 strings)
French translated at 86.8% (965 of 1111 strings)
English translated at 86.8% (965 of 1111 strings)
Italian translated at 86.6% (963 of 1111 strings)
Esperanto translated at 46.5% (517 of 1111 strings)
Norwegian Bokmål translated at 9.6% (107 of 1111 strings)
Co-authored-by: Nicolas Prongué <n.prongue@outlook.com>
Co-authored-by: iGor milhit <igor.milhit@rero.ch>
Translate-URL: https://hosted.weblate.org/projects/rero_plus/sonar/
Translation: RERO+/sonar
> translations: update catalog

- setup.py
- sonar/config_sonar.py
- sonar/modules/ark/__init__.py
- sonar/modules/ark/api.py
- sonar/modules/ark/cli.py
- sonar/modules/documents/api.py
- sonar/modules/documents/extensions.py
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/mappings/v7/documents/document-v1.0.0.json
- sonar/modules/documents/marshmallow/json.py
- sonar/modules/documents/minters.py
- sonar/modules/documents/templates/documents/record.html
- tests/api/documents/test_documents_permissions.py
- tests/conftest.py
- tests/ui/documents/cli/test_documents_cli_ark.py
- tests/ui/documents/test_documents_views.py
- tests/utils.py
* Adds command line interface to interact with a NMA ARK server.
* Mints a new ARK identifier when a document is created.
* Registers the ARK identifier at the document creation.
* Marks the ARK persistent identifier as deleted when the document is
removed.
* Replace the persistent URL by the ARK resolver URL if it is relevant.
* Closes rero#399.
Co-Authored-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>
> identifiers: add ARK identifiers

- setup.py
- sonar/config_sonar.py
- sonar/dedicated/templates/dedicated/hepvs/home.html
- sonar/dedicated/views.py
- sonar/modules/organisations/jsonschemas/organisations/organisation-v1.0.0_src.json
- sonar/theme/templates/sonar/frontpage.html
- sonar/theme/templates/sonar/page.html
* Adds the possibility to define a custom template for the homepage of a dedicated organisation.
* Creates a blueprint for dedicated templates.
* Configures homepage template for HEPVS.
* Hides `allowedIps` in editor if the organisation is not shared.
* Hides label for custom fields by default.
* Moves field `platformName` after `allowedIps`.
* Closes #583.
> homepage: custom description for organisations

- sonar/modules/documents/dojson/rerodoc/model.py
- sonar/modules/documents/dojson/rerodoc/overdo.py
- tests/ui/documents/dojson/rerodoc/test_rerodoc_model.py
- tests/ui/documents/test_dc_schema.py
- tests/unit/documents/loaders/test_rerodoc_loader.py
- tests/unit/documents/serializers/test_schemaorg_schema.py
Fixes the license value for documents imported from RERO DOC, as the name has changed.
> documents: fix license for RERO DOC publications

- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
* Fixes projects typehead in document editor by adding the label field to display in JSON schema.
* Closes #593.
> documents: fix projects typehead

- sonar/modules/documents/templates/documents/record.html
* Searches on `subjects` field instead of all fields when clicking on a subject.
* Closes #367.
> documents: subjects search

- sonar/modules/pdf_extractor/utils.py
- tests/ui/pdf_extractor/test_pdf_extractor_utils.py
* Fixes an error with the date property when the PDF contains an host document.
* Closes #603.
> deposits: fix PDF date extraction

- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/mappings/v7/documents/document-v1.0.0.json
- sonar/modules/documents/marshmallow/json.py
- sonar/modules/documents/query.py
- tests/api/documents/test_documents_query.py
* Adds `marked` property to documents and hides masked documents on the public interface.
* Closes #570.
> documents: add `masked` property

- sonar/modules/organisations/permissions.py
- tests/api/organisations/test_organisations_permissions.py
Allows users with `superuser` role to remove an organisation.
> organisations: remove an organisation

- .github/workflows/continuous-integration-test.yml
- poetry.lock
- pyproject.toml
security: update dependencies 
* Upgrades pillow and coverage version.
* Allows pre-release for invenio-records.
* Freezes celery version to 5.0.5 to avoid an error.
* Installs coveralls from outside of poetry in CI integration.
> security: update dependencies

- sonar/modules/deposits/templates/deposits/email/approve/en.txt
- sonar/modules/deposits/templates/deposits/email/ask_for_changes/en.txt
- sonar/modules/deposits/templates/deposits/email/reject/en.txt
* Removes moderator information in the emails sent to users during the
deposit process.
* Closes #551.
> deposits: change validation process emails

- setup.py
- sonar/modules/cli/__init__.py
- sonar/modules/cli/fixtures.py
- sonar/modules/cli/imports.py
- sonar/modules/cli/utils.py
- sonar/modules/documents/tasks.py
- tests/ui/test_cli.py
* Adds a CLI to import records from HEP BEJUNE file.
* Moves SONAR CLI commands to a specific folder.
* Adds the ability to import a file not from an URL, but from local
path.
* Closes #620.
> documents: import records from HEP BEJUNE

- sonar/theme/templates/sonar/partial/navbar.html
* Adds a button in the navbar to quickly deposit a publication, only for submitters.
* Closes #366.
> deposit: add a call to action

- sonar/config.py
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/mappings/v7/documents/document-v1.0.0.json
- sonar/modules/documents/marshmallow/json.py
- sonar/modules/documents/query.py
- sonar/modules/documents/receivers.py
- sonar/modules/documents/views.py
- sonar/modules/utils.py
- tests/api/documents/test_documents_query.py
- tests/ui/test_utils.py
* Allows to display documents only for allowed IP addresses. This is
done by changing the `masked` property from a boolean to an enum.
* Configures facet for filtering documents with `masked` property.
* Closes #632.
> documents: `masked` property enhancement

- setup.py
- sonar/config_sonar.py
- sonar/modules/deposits/api.py
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
- sonar/modules/deposits/mappings/v7/deposits/deposit-v1.0.0.json
- sonar/modules/deposits/serializers/schemas/document.py
- sonar/modules/documents/dojson/overdo.py
- sonar/modules/documents/dojson/rerodoc/overdo.py
- sonar/modules/documents/dojson/sru/__init__.py
- sonar/modules/documents/dojson/sru/model.py
- sonar/modules/documents/loaders/schemas/sru.py
- sonar/modules/documents/marshmallow/json.py
- sonar/modules/permissions.py
- sonar/modules/swisscovery/__init__.py
- sonar/modules/swisscovery/rest.py
- tests/api/swisscovery/test_swisscovery_rest.py
- tests/conftest.py
- tests/ui/deposits/test_deposits_api.py
- tests/ui/deposits/test_deposits_documents_schema.py
- tests/ui/documents/schemas/test_sru_schema.py
* Adds an endpoint to search for swisscovery records.
* Adds a loader to transform swisscovery record to document record.
* Adds a serializer to transform document record to deposit record.
* Closes #610.
> api: search swisscovery records

- setup.py
- sonar/modules/documents/rest.py
- sonar/modules/documents/serializers/__init__.py
- tests/api/documents/test_documents_permissions.py
- tests/api/documents/test_documents_query.py
- tests/api/documents/test_documents_rest.py
- tests/api/subdivisions/test_subdivisions_documents_facets.py
* Adds an endpoint to get the aggregations order for the documents.
* Moves logic for displaying facets into the new endpoint instead of
the search serializer.
* Closes #623.
> search: aggregations order endpoint

- sonar/common/jsonschemas/masked-v1.0.0.json
- sonar/modules/deposits/api.py
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
- sonar/modules/deposits/mappings/v7/deposits/deposit-v1.0.0.json
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- tests/conftest.py
- tests/ui/deposits/test_deposits_api.py
* Puts the masked property in a common JSONSchema file.
* Copy the masked property from the deposit to the document.
* Fixes deposit JSONSchema where the `additionalProperties` was missing.
* Closes rero#640.
> deposit: allow to set document visibility

- sonar/modules/documents/dojson/rerodoc/model.py
- tests/ui/documents/dojson/rerodoc/test_rerodoc_model.py
> documents: try to parse the thesis note from RERO DOC more precisely

- sonar/dedicated/templates/dedicated/hepvs/home.html
- sonar/modules/documents/dojson/rerodoc/model.py
- sonar/modules/documents/loaders/schemas/rerodoc.py
- sonar/modules/documents/rest.py
* adds specific transformation to RERO DOC import for ROAR,
in order to fill out custom fields `Filière` (`customField1`)
and `Titre obtenu` (`customField2`)
* fixes bug in customField facet label definition
* fixes typo in FREDI description
> documents: fill out custom fields for ROAR during RERO DOC import

- poetry.lock
- pyproject.toml
- scripts/test
* Adds a new contraint for werkzeug > 2.0.1.
* Adds a new contraint for  bleach > 3.11.
* Adds a new excption for sqlalchemy-utils as this package has no safe
version.
Co-Authored-by:Johnny Mariéthoz <johnny.mariethoz@rero.ch>
> dependencies: fix several packages version for security reasons

- data/organisations/data.json
- sonar/common/jsonschemas/interface_language-v1.0.0.json
- sonar/modules/organisations/jsonschemas/organisations/organisation-v1.0.0_src.json
- sonar/modules/organisations/mappings/v7/organisations/organisation-v1.0.0.json
- sonar/modules/organisations/marshmallow/json.py
- sonar/modules/organisations/serializers/schemas/export.py
- sonar/theme/templates/sonar/footer.html
- sonar/theme/templates/sonar/frontpage.html
- sonar/theme/templates/sonar/partial/organisation.html
- sonar/theme/templates/sonar/partial/switch_aai_dropdown.html
* Changes Powered by RERO+ by Powered by SONAR in the footer.
* Closes #682. 
> organisations: implement multilingual footer for dedicated

- sonar/modules/api.py
- sonar/modules/deposits/api.py
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
- sonar/modules/deposits/query.py
- tests/api/deposits/test_deposits_permissions.py
- tests/conftest.py
- tests/ui/deposits/test_deposits_api.py
* Solves a problem that prevented a moderator to see the deposits
of his/her subdivision in the list of deposits.
* Adds a second subdivision test fixture.
* Closes rero#631.
> subdivisions: fix moderator access bug

- sonar/common/jsonschemas/license-v1.0.0.json
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
* Fixes the validation of a deposit by a moderator when the license is
not defined.
* Makes the license required in the deposit form.
* Fixes missing fields for book chapter.
Co-Authored-by: Johnny Mariéthoz <johnny.mariethoz@rero.ch>
> deposit: fix moderator validation

- sonar/modules/documents/dojson/rerodoc/model.py
- tests/ui/documents/dojson/rerodoc/test_rerodoc_model.py
- tests/unit/documents/loaders/test_rerodoc_loader.py
* When MARC field 775 $o contains a DOI in RERO DOC, its value is
imported in the `identifiedBy` field instead of `otherEdition`.
* Closes #659.
> Identify DOI in RERO DOC field 775 $o

- scripts/test
- sonar/modules/users/templates/users/email/welcome/en.html
- sonar/modules/users/utils.py
> fix user welcome email

- sonar/modules/documents/dojson/rerodoc/model.py
* Import documents to the subdivision "HEP Fribourg" and the faculty "HEP|PH FR" within FOLIA.
> documents: import HEP FR publications from RERO DOC to FOLIA

- sonar/modules/documents/dojson/rerodoc/model.py
- tests/api/test_api_simple_flow.py
- tests/conftest.py
- tests/ui/deposits/test_deposits_api.py
- tests/ui/documents/test_dc_schema.py
- tests/ui/documents/test_documents_api.py
- tests/ui/documents/test_documents_utils.py
- tests/ui/test_query.py
* Creates a new embargo date fixture in one year in the future.
* Removes all hard coded embargo date in the tests.
> tests: fix hardcoded embargo date

- sonar/modules/documents/dojson/rerodoc/model.py
- sonar/theme/views.py
- tests/ui/test_views.py
* Adds redirections for files.
* Adds redirections the dedicated or shared views.
> rerodoc: redirection to the correct views

- setup.py
- sonar/config.py
- sonar/dedicated/__init__.py
- sonar/ext.py
- sonar/help/__init__.py
- sonar/help/templates/help/page_wiki.html
- sonar/help/templates/help/page_wiki_search.html
- sonar/help/templates/help/page_wiki_search_navigation.html
- sonar/help/views.py
- sonar/theme/templates/sonar/footer.html
- sonar/theme/templates/sonar/page_wiki.html
The help is displayed with the organization's code
and is no longer directed to the global help.
* Closes #709.
* Closes #712.
- Url for organization help: https://sonar/{view}/help
> help: display with the organization's code

- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/views.py
- tests/ui/documents/test_documents_views.py
* Distinguish between thesis supervisor and co-supervisors
* Adds dgc "Degree committee member" for field contribution.role in document and deposit.
* Closes #733
> schema: distinguish supervisor co-supervisors

- sonar/config.py
- sonar/modules/documents/rest.py
- sonar/modules/organisations/jsonschemas/organisations/organisation-v1.0.0_src.json
- sonar/modules/organisations/mappings/v7/organisations/organisation-v1.0.0.json
- sonar/modules/organisations/marshmallow/json.py
- sonar/modules/organisations/serializers/schemas/export.py
* updates security policy to allow maxcdn.bootstrapcdn.com.
* closes rero#702.
⚠️  **Update ES mapping with the new field in documents**
- Sonar ui: https://github.com/rero/sonar-ui/pull/281
- Login with a super user
- Go to the administration interface
- Administration menu > Organization
- Edit a dedicated organization
- Select the desired facets (at the bottom of the window)
- Check on the public interface
> organisation: custom facet implementation for dedicated customers

- sonar/modules/documents/mappings/v7/documents/document-v1.0.0.json
- sonar/modules/utils.py
- tests/api/documents/test_documents_query.py
- tests/ui/test_utils.py
* Fixes slow OAI-PHM requests that returns 500 errors.
* Fixes slow document api requests.
Note: this requires a data migration, the document index should be
recreated.
- Check the document filtered by IPs.
- Check the file and document access restricted by IPs.
> documents: store allowed ips addresses in CIDR format

- docker-compose.full.yml
- scripts/server
- scripts/setup
- sonar/celery.py
* Adds dotenv support to celery to make the worker working with a custom
celery backend from `invenio.cfg`.
> celery: add dotenv support

- sonar/modules/documents/templates/documents/record.html
- sonar/modules/documents/views.py
- sonar/theme/templates/sonar/page.html
- sonar/theme/templates/sonar/search.html
Remove the document organisation tag from the public interface
on the brief and detailed view if the display is not on the global view.
* Closes #726.
- https://github.com/rero/sonar-ui/pull/292
> documents: remove organisation tag

- sonar/modules/swisscovery/rest.py
- tests/api/swisscovery/test_swisscovery_rest.py
* Closes #701.
- Add a deposit and import source swisscovery with identifier: 2070406237
> swisscovery: remove << and >> characters in the title when importing

- sonar/ext.py
- sonar/theme/templates/sonar/frontpage.html
- sonar/theme/templates/sonar/partial/navbar.html
- sonar/theme/templates/sonar/partial/organisation.html
> frontend: header size for shared organisation

- sonar/config_sonar.py
- sonar/modules/documents/templates/documents/record.html
- sonar/theme/templates/sonar/macros/macro.html
- sonar/theme/views.py
- tests/ui/test_views.py
* Closes #711.
- Check identifiers on identifiedBy for the document detailed view.
- Check identifiers on agent for the document detailed view.
- Check identifiers for the project detailed view.
- https://github.com/rero/sonar-ui/pull/294
> documents: add a configuration for links on identifiers

- sonar/ext.py
- sonar/modules/collections/views.py
- sonar/modules/organisations/utils.py
- sonar/modules/users/utils.py
- sonar/theme/templates/sonar/page.html
- tests/unit/organisations/test_organisations_utils.py
* Adds the display of the custom favicon for current organisation.
* Adds the organization's platform name to the browser tab.
* Closes #705.
- Upload favicon.ico to organisation files.
- Check the organisation favicon and name in browser tab.
> organisations: favicon and platform name

- sonar/config.py
- sonar/modules/documents/serializers/__init__.py
- sonar/modules/documents/serializers/dc.py
- sonar/modules/documents/serializers/schemas/dc.py
- tests/ui/documents/test_dc_schema.py
> oai: fix error on document type processing

- sonar/modules/deposits/api.py
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
- sonar/modules/deposits/mappings/v7/deposits/deposit-v1.0.0.json
- sonar/modules/deposits/serializers/schemas/document.py
- tests/ui/deposits/test_deposits_documents_schema.py
* Adds 2 fields date_of_birth and date_of_death in deposit json schema.
* Updates of the import of these 2 new fields.
* Closes #791.
> swisscovery: import of the contributor's date of birth and death

- sonar/modules/documents/views.py
- tests/ui/documents/test_documents_views.py
The languages of the abstracts that are not in the preferred
sorting languages are added at the end of the list and sorted
alphabetically by language code.
* Fixes Sentry SONAR-EA.
> documents: fix abstracts sort

- scripts/test
> security: exclude click

- sonar/config_sonar.py
- sonar/modules/documents/urn.py
- sonar/monitoring/views/__init__.py
- tests/api/conftest.py
- tests/api/monitoring/test_monitoring_views.py
- tests/ui/documents/test_document_urn.py
A new api to count documents with unregistered pids
with an optional parameters `days`.
* Completes urn config for two organisations.
* 
Co-Authored-by: Aly Badr <aly.badr@rero.ch>
> urn: monitor count of unregistered pids by days

- poetry.lock
- pyproject.toml
- sonar/config.py
- sonar/theme/templates/sonar/page_wiki.html
* updates flask-wiki to `v0.1.0` with EasyMDE integration
- Log in as superuser
- Open the help and edit a page
- If you don't see the new editor, disable the cache
- Check the new markdown editor and check that everything works as expected.
> help: update flask-wiki

- sonar/modules/documents/api.py
- sonar/modules/documents/cli/urn.py
- sonar/modules/documents/extensions.py
- sonar/modules/documents/models.py
- sonar/modules/documents/tasks.py
- sonar/modules/documents/urn.py
- sonar/modules/utils.py
- tests/api/monitoring/test_monitoring_views.py
- tests/ui/documents/test_document_urn.py
- tests/ui/documents/test_documents_tasks.py
* Adds a celery task after document creation for urn registry.
* Adds cli to register urn codes.
* Creates a separate identifier for urn codes.
Co-Authored-by: Aly Badr <aly.badr@rero.ch>
> urn: implement registry mechanism

- .github/workflows/continuous-integration-test.yml
- poetry.lock
- scripts/setup
- sonar/config.py
- sonar/ext.py
- sonar/modules/stats/config.py
- sonar/signals.py
- sonar/theme/templates/sonar/stats/index.html
- tests/api/documents/test_documents_files_rest.py
- tests/conftest.py
Due to invenio isssues, the file download statistics are not enabled.
See: https://github.com/inveniosoftware/invenio-stats/issues/116 for
more details.
To test the API try a POST on /api/stats with:
```json
{
"view": {
"stat": "record-view",
"params": {
"pid_value": "81",
"pid_type": "doc"
}
},
"download": {
"stat": "file-download",
"params": {
"bucket_id": "f9075edd-fbe7-44ad-bb73-b1b88bd5c70c"
}
}
}
```
You should have a response like:
```json
{
"download": {
"bucket_id": "f9075edd-fbe7-44ad-bb73-b1b88bd5c70c",
"buckets": [
{
"count": 1,
"key": "2022INF001-pdf.jpg", …
```
> statistics: enable file download statistics

- docker/uwsgi/uwsgi_rest.ini
- docker/uwsgi/uwsgi_ui.ini
> uwsgi: suppress unimportant errors

- sonar/modules/documents/mappings/v7/documents/document-v1.0.0.json
- sonar/modules/users/mappings/v7/users/user-v1.0.0.json
- sonar/resources/projects/mappings/v7/projects/project-v1.0.0.json
The default size of the suggestion field is 50. It has been increased to 100.
* Closes #853.
⚠️  ES reindexing: documents, projects and users.
> documents: Increase the size of the suggested field

- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
* `volume`, `number` and `pages` deposit fields should not reject values
that are accepted by the equivalent fields in the document.
* Allows more flexibility for submitters and prevents API rejections
* Closes https://github.com/rero/sonar/issues/878
> deposits: harmonize field validations

- poetry.lock
- pyproject.toml
- sonar/theme/templates/sonar/page.html
- sonar/theme/templates/sonar/page_wiki.html
* Updates flask-wiki to latest version
* Removes container in wiki template to use full width of the page
> update flask-wiki to 0.2.1

- sonar/ext.py
Register validation blueprint.
When a project is submitted a validation email is sent to reviewers. The body of the email is a template defined in the validation module. To make the template reachable the blueprint 'validation' needs to be registered.
Closes  https://github.com/rero/sonar/issues/858
issue https://github.com/rero/sonar/issues/858
> validation: register validation blueprint

- sonar/modules/documents/api.py
- sonar/modules/documents/templates/documents/record.html
- sonar/theme/templates/sonar/macros/macro.html
- sonar/theme/templates/sonar/projects/detail.html
- tests/ui/documents/test_documents_api.py
- tests/ui/documents/test_documents_receivers.py
* Adds a statistics property to the documents api.
* Adds the number of document view and file downloads on the documents detailed view.
Issue: https://github.com/rero/sonar/issues/400
This PR depends on:
https://github.com/rero/sonar-ui/pull/316
> record: add record statistics on the public detailed view

- data/organisations/data.json
- pyproject.toml
- sonar/config.py
- sonar/config_sonar.py
- sonar/ext.py
- sonar/modules/organisations/api.py
- sonar/modules/organisations/jsonschemas/organisations/organisation-v1.0.0_src.json
- sonar/modules/organisations/mappings/v7/organisations/organisation-v1.0.0.json
- sonar/modules/organisations/marshmallow/json.py
- sonar/modules/sitemap/__init__.py
- sonar/modules/sitemap/cli/sitemap.py
- sonar/modules/sitemap/sitemap.py
- sonar/modules/sitemap/tasks.py
- sonar/modules/sitemap/templates/sonar/sitemap.xml
- sonar/modules/sitemap/templates/sonar/sitemap_index.xml
- sonar/modules/sitemap/views.py
- sonar/theme/templates/sonar/robots.txt
- sonar/theme/views.py
- tests/conftest.py
- tests/ui/sitemap/test_sitemap.py
- tests/ui/sitemap/test_sitemap_views.py
- tests/ui/test_views.py
* Adds a new field serverName on organisation resource.
* Implements sitemap generation for global and dedicated organisations.
* Implements generation of the file robot.txt dynamically.
* Closes #798.
⚠️ **ES update mapping**
⚠️ **Production**
* make the flag **True** on INVENIO_SONAR_APP_PRODUCTION_STATE
* set  INVENIO_SONAR_APP_SITEMAP_FOLDER_PATH
- `poetry shell` 
- `./script/bootstrap`
- `./script/setup --clear-data`
- `invenio oaiharvester harvest -n rerodoc -q -a max=200 -f 2021-10-01`
- `invenio sitemap generate -d sonar.rero.ch` (for global view)
- `invenio sitemap generate -d folia.unifr.ch` (for global view)
- Global sitemap: `https://localhost:5000/global/sitemap.xml`
- Organisation sitemap: …
> add sitemap functionality

- sonar/modules/organisations/marshmallow/json.py
* Fixes the `serverName` field not accepted by the server in the
dedicated organisation editor, preventing to save.
> organisations: fix editor ValidationError

- pyproject.toml
- sonar/alembic/3d3309f660e4_init.py
- sonar/alembic/e1eb7549728f_replace_document_type_field_in_documents.py
- sonar/common/jsonschemas/type-v1.0.0.json
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/serializers/schemas/schemaorg.py
- tests/ui/users/test_user_jsonresolvers.py
* Adds conference object and book review document types for documents
and deposits.
* Changes value and label for document_type_other for better clarity.
* Initializes alembic.
* Includes alembic script for db migration.
* Closes #881.
* Closes #626.
* Makes the `status` deposit field required to prevent submitting
a deposit with no status from the API.
> jsonschemas: add 2 new document types

- poetry.lock
- sonar/modules/documents/views.py
- tests/conftest.py
- tests/ui/documents/test_documents_views.py
- tests/unit/documents/serializers/test_document_json_schema.py
* Fixes missing contributions in the `partOf` field.
* Updates `wand` package for apple M1.
* Take into account `.env` file for the tests.
> documents api: fix missing contribution

- CHANGELOG.md
- pyproject.toml
- sonar/config_sonar.py
- sonar/version.py
> release: v1.8.0

- sonar/modules/documents/api.py
- sonar/modules/documents/permissions.py
- sonar/modules/documents/urn.py
- tests/api/documents/test_documents_files_permissions.py
- tests/api/documents/test_documents_permissions.py
Add permissions for documents with registered URN:
- prevent deleting documents with registered URN
- prevent deleting pdf files of documents with registered URN
issue https://github.com/rero/sonar/issues/849
> documents: add permissions for documents with registred URN

- .github/workflows/continuous-integration-test.yml
- Dockerfile
- Dockerfile.base
- poetry.lock
- pyproject.toml
- scripts/bootstrap
- scripts/test
- sonar/modules/documents/serializers/dc.py
- tests/ui/documents/test_dc_schema.py
* Adds new `safety` exceptions.
* Removes controls chars when the dublin core xml file is produced.
* Closes https://github.com/rero/sonar/issues/867.
* Updated docker base image.
* Adds a second test scenario with latest dependencies versions.
* Fixes dependencies with last versions.
* Copies static files for productions.
* Adds --ci option for the bootstrap script.
> fix: OAI-PMH crash for document containing control chars

- sonar/modules/documents/api.py
- tests/ui/documents/test_documents_api.py
* Closes #807.
* Removes controlled affiliations because sometimes a controlled
affiliation becomes uncontrolled.
Co-Authored-by:  Pascal Repond <pascal.repond@rero.ch>
> documents: clear controlled affiliations

- sonar/modules/documents/permissions.py
- sonar/modules/documents/urn.py
- tests/api/documents/test_documents_files_permissions.py
- tests/api/documents/test_documents_permissions.py
Add permissions for documents with registered URN:
-  prevent deleting documents with registered URN
-  prevent deleting pdf files of documents with registered URN
This PR is a copy of https://github.com/rero/sonar/pull/898.
issue https://github.com/rero/sonar/issues/849
> documents: permissions delete for documents with registred URN

- sonar/config.py
ORCID has changed their base URL for oauth. The old URL is a redirect which
is not supported by invenio.
> orcid: change legacy URL

- docker/nginx/Dockerfile
- docker/nginx/conf.d/default.conf
* Adapts the nginx configuration for the last nginx docker version.
> deployement: fix nginx configuration

- sonar/config_sonar.py
- sonar/modules/documents/marshmallow/__init__.py
- sonar/modules/documents/marshmallow/json.py
- sonar/modules/documents/serializers/__init__.py
* Removes the files permissions for the document list serializer.
> documents: fix poor performance on serializer

- sonar/monitoring/api/data_integrity.py
- sonar/monitoring/api/database.py
- sonar/monitoring/views/__init__.py
- tests/api/monitoring/test_monitoring_views.py
- tests/unit/monitoring/test_api_db_connection.py
* Renames blueprints to match reroils.
* Adds REDIS and ES indicies monitoring.
* Corrects ES-DB monitoring for projects.
> monitoring: REDIS, ES indicies

- sonar/config_sonar.py
- sonar/modules/documents/utils.py
- sonar/modules/utils.py
- tests/api/documents/test_documents_files_rest.py
- tests/ui/documents/test_documents_utils.py
- tests/ui/test_utils.py
* Adds tests to support accents in file names.
* Fixes preview links when a filename contains multiple dots.
> files: fix preview button for file name contining dots

- sonar/modules/documents/mappings/v7/documents/document-v1.0.0.json
- tests/api/documents/test_documents_query.py
* Allows to query the document identifiers with partial values such as: identifiers.local.text:(R003415*).
> documents: add wildcard query to document identifiers

- poetry.lock
- pyproject.toml
- sonar/modules/documents/marshmallow/json.py
- tests/api/documents/test_documents_rest.py
* Removes the useless files permissions from the search list to speed up the server responses.
> documents: removes permssions from the search list

- pyproject.toml
- sonar/modules/documents/receivers.py
- tests/api/test_api_query.py
* Adds boostring support for field with fields sub properties.
> documents: fix boosting

- .github/workflows/continuous-integration-test.yml
- INSTALL.rst
- docker-compose.yml
- docker/wait-for-services.sh
- poetry.lock
- scripts/test
* Linked to deprecation of Docker Compose v1 in Github Actions: https://github.com/actions/runner-images/issues/9692
* Updates dependencies and fixes safety tests.
> chore(deprecation): update compose commands to v2

- sonar/modules/documents/templates/documents/record.html
* Displays the classification even if it is of type Ddc.
* Make the links to classifications and subjects more robust with quotes.
* Closes #859.
> fix(document): fix links to classifications and subjects

- pyproject.toml
- sonar/modules/documents/api.py
- sonar/modules/subdivisions/permissions.py
- sonar/modules/users/api.py
- sonar/modules/users/tasks.py
- tests/api/subdivisions/test_subdivisions_permissions.py
- tests/ui/documents/test_documents_api.py
- tests/ui/users/test_users_api.py
* Deletes corresponding deposit during document deletion.
* Deletes corresponding deposits during user deletion.
* Prevent deleting a subdivision if it has any linked user or deposit.
* Closes #948.
> fix: add cascading deletions to improve data consistency

- sonar/config.py
- sonar/modules/documents/marshmallow/__init__.py
- sonar/modules/documents/marshmallow/json.py
- sonar/modules/documents/serializers/__init__.py
- tests/api/documents/test_documents_rest.py
* Removes unused DeepDiff python package.
* Extends document tests REST API.
* Adds alias format for documents.
* Creates a new marshmallow serializer that removes the ark values form the identifiers.
Depends on:
- https://github.com/rero/ng-core/pull/751
- https://github.com/rero/sonar-ui/pull/413
> fix: disallows ark identifier modifications
