- docker/nginx/conf.d/default.conf
* Change of server location to work with kubernetes
Signedoff-by: Sébastien Délèze <sebastien.deleze@rero.ch>
> deployment: change server location

- docker/nginx/conf.d/default.conf
> deployment: static directory map change

- run-tests.sh
- tests/e2e/test_front_page.py
* FIX Ignore vulnerability problem related on numpy
* FIX Change frontpage test case
> tests: Travis build

- Pipfile
- Pipfile.lock
- docker-services.yml
- sonar/config.py
- sonar/theme/views.py
* NEW Added minial sentry configuration and dependencies.
> config: Sentry support

- sonar/theme/templates/sonar/partial/navbar.html
NEW Switch language in navbar.
> translations: Language switcher

- sonar/config.py
- sonar/translations/fr/LC_MESSAGES/messages.po
- sonar/translations/it/LC_MESSAGES/messages.po
- sonar/translations/messages.pot
BETTER Add italian translations.
> translations: Italian translations

- sonar/modules/documents/cli.py
- tests/ui/documents/test_documents_cli.py
- tests/ui/documents/test_marc21tojson.py
BETTER Mock functions responses to increase code coverage.
> tests: Increase code coverage

- README.rst
- sonar/version.py
* NEW Add release tag to README file.
> project: Release tag

- docker-services.yml
- setup.py
- sonar/config.py
- sonar/modules/api.py
- sonar/modules/deposits/api.py
- sonar/modules/deposits/jsonschemas/__init__.py
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0.json
- sonar/modules/deposits/mappings/__init__.py
- sonar/modules/deposits/mappings/v6/__init__.py
- sonar/modules/deposits/mappings/v6/deposits/deposit-v1.0.0.json
- sonar/modules/deposits/rest.py
- sonar/modules/deposits/utils.py
- sonar/modules/pdf_extractor/utils.py
- sonar/modules/pdf_extractor/views/api.py
- sonar/modules/permissions.py
- sonar/modules/users/api.py
- sonar/modules/users/jsonresolvers.py
- sonar/theme/views.py
- tests/ui/conftest.py
- tests/ui/deposits/test_deposits_cli.py
- tests/ui/deposits/test_deposits_utils.py
- tests/ui/test_views.py
- tests/ui/users/test_user_jsonresolvers.py
* Creates a deposit resource with JSON schema and elasticsearch indexing.
* Adds configuration for allow disabling permission checks.
* Provides API endpoint for retreiving logged user.
* Adds a custom REST endpoint for handling file upload.
* Improves users fixtures creation.
* Closes #82.
> resources: create deposit resource

- MANIFEST.in
- sonar/config.py
- sonar/modules/api.py
- sonar/modules/deposits/api.py
- sonar/modules/deposits/rest.py
- sonar/modules/deposits/templates/email/validation.en.txt
- sonar/modules/permissions.py
- sonar/modules/users/api.py
- sonar/utils.py
- tests/ui/conftest.py
- tests/ui/deposits/data/extracted_data.json
- tests/ui/deposits/test_deposits_api.py
- tests/ui/test_api.py
- tests/ui/test_permissions.py
- tests/ui/users/test_users_api.py
* Adds aggregation filters for deposit resource.
* Adds a common function to send emails.
* Creates an API endpoint to publish/submit a deposit.
* Increases code coverage.
* Closes #91.
> deposit: publish a deposit

- sonar/modules/deposits/api.py
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0.json
- sonar/modules/deposits/rest.py
- sonar/modules/deposits/templates/email/approve.en.txt
- sonar/modules/deposits/templates/email/ask-for-changes.en.txt
- sonar/modules/deposits/templates/email/reject.en.txt
- sonar/modules/deposits/templates/email/validation.en.txt
- sonar/modules/users/api.py
- sonar/theme/views.py
- tests/api/conftest.py
- tests/api/deposits/test_deposits_rest.py
- tests/ui/users/test_users_api.py
deposit: review a deposit
* Adds an API endpoint to review a deposit.
* Adds properties to UserRecord to know the role of the user.
* Logs intervention during deposit review process.
> deposit: review a deposit

- setup.py
- sonar/bundles.py
- sonar/theme/templates/sonar/manage.html
- tests/ui/test_views.py
* Renames UI project and generated files.
* Updates sonar-ui version to 0.1.2.
> ui: update project name

- Pipfile
- Pipfile.lock
* Upgrades Invenio to stable version 3.2.
> project: upgrade Invenio

- setup.py
* Loads ShibbolethAuthenticator extension for fixing config issue.
> shibboleth: fix authentication issue

- sonar/modules/ext.py
- sonar/modules/pdf_extractor/utils.py
- sonar/modules/permissions.py
- sonar/theme/assets/scss/common/_theme.scss
- sonar/theme/templates/sonar/partial/dropdown_user.html
- sonar/theme/webpack.py
- tests/ui/test_permissions.py
* Adds styles for ngx-toastr.
* Avoids error on PDF extraction when forename is not existing.
* Gives access to deposit for users with role user.
> deposit: various corrections

- sonar/config.py
- sonar/theme/templates/sonar/accounts/reset_password.html
* Modifies the template for resetting password.
> account: password forgotten template

- sonar/modules/documents/dojson/contrib/marc21tojson/model.py
- sonar/modules/documents/dojson/utils.py
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/mappings/v6/documents/document-v1.0.0.json
- sonar/modules/documents/templates/documents/record.html
- tests/ui/documents/test_marc21tojson.py
* Fixes display of languages facet by importing languages correctly.
* Fixes #123.
> records: fix languages facet display

- setup.py
- sonar/theme/api_views.py
- tests/ui/data/json_to_compile.json
- tests/ui/test_api_views.py
* Creates an API endpoint to get the JSON schema corresponding to a resource.
> records: JSON schema API endpoint

- MANIFEST.in
- scripts/install-ui
* Adds a script to install a specific pack of UI from file.
* Fixes an issue when copying files from assets to static.
> project: install UI script

- sonar/modules/deposits/rest.py
- tests/api/deposits/test_deposits_rest.py
- tests/conftest.py
* Not extracts metadata on upload anymore.
* Provides a REST endpoint for extracting metadata.
> deposit: PDF metadata extraction

- sonar/config.py
- sonar/modules/documents/templates/documents/record.html
- sonar/modules/documents/views.py
- tests/ui/documents/test_documents_views.py
* Adds a link to preview PDF in detail view.
* Lists only files with type "file" in detail view.
> documents: PDF preview

- sonar/config.py
* Configures UI endpoint to display file preview.
* Allow blob data in content security policy for file preview plugin to work.
> deposit: File preview

- sonar/modules/documents/dojson/contrib/marc21tojson/model.py
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/mappings/v6/documents/document-v1.0.0.json
- sonar/modules/documents/templates/documents/record.html
- tests/ui/documents/test_marc21tojson.py
* Extracts and imports other editions from field 775.
* Displays other editions in detail view.
> documents: import other editions

- sonar/theme/static/images/orcid.svg
- sonar/theme/templates/sonar/accounts/login.html
- sonar/theme/templates/sonar/accounts/signup.html
* Adds ORCID icon to sign-up and sign-in with ORCID button.
> accounts: add ORCID icon

- sonar/modules/deposits/api.py
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
- sonar/modules/pdf_extractor/utils.py
- sonar/translations/de/LC_MESSAGES/messages.po
- sonar/translations/en/LC_MESSAGES/messages.po
- sonar/translations/fr/LC_MESSAGES/messages.po
- sonar/translations/it/LC_MESSAGES/messages.po
- sonar/translations/messages.pot
- tests/ui/deposits/test_deposits_api.py
* Removes `classification` from the required fields.
* Adds the possibility to fill a full date for document date field.
* Renames `title` property for publication.
* Removes `pages` from required fields in publication.
* Hides or shows publication depending on document type.
* Adds a placeholder for `pages` property in publications.
* Adds a placeholder for document date.
* Removes `affiliation` from required fields in contributors.
* Closes #rero/sonar-ui#62.
* Closes #rero/sonar-ui#68.
1. Go to Administration > Deposit a publication
2. Fill the form and check placeholders, constraints.
3. Change document type and check "Publication" fields are shown/hidden.
> deposit: improve form in submission process

- sonar/translations/de/LC_MESSAGES/messages.po
- sonar/translations/en/LC_MESSAGES/messages.po
- sonar/translations/fr/LC_MESSAGES/messages.po
- sonar/translations/it/LC_MESSAGES/messages.po
* Adds translations for non-human readable keys.
> translations: add translations

- sonar/theme/assets/scss/common/_theme.scss
- sonar/theme/assets/scss/common/_variables.scss
- sonar/theme/templates/sonar/frontpage.html
- sonar/theme/templates/sonar/partial/navbar.html
* Changes font family from `Roboto Condensed` to `Roboto`.
* Changes top header background color.
* Minimizes `Software under development` banner.
* Closes #211.
> design: rebrand website

- sonar/config.py
- sonar/modules/documents/mappings/v6/documents/document-v1.0.0.json
- sonar/modules/documents/serializers/__init__.py
- sonar/modules/serializers.py
- sonar/theme/templates/sonar/manage.html
- sonar/theme/templates/sonar/search.html
- sonar/translations/de/LC_MESSAGES/messages.po
- sonar/translations/en/LC_MESSAGES/messages.po
- sonar/translations/fr/LC_MESSAGES/messages.po
- sonar/translations/it/LC_MESSAGES/messages.po
- sonar/translations/messages.pot
- tests/api/documents/test_documents_permissions.py
* Adds aggregation and filter for controlled affiliations.
* Adds aggregation and filter for authors.
* Adds aggregation and filter for start date.
* Adds a method to post process result in main serializer.
* Modifies year aggregation in post process for adding min and max value.
* Changes mapping for fields used in new aggregations.
* Closes #212.
* Closes #213.
* Closes #214.
> search: add aggregations

- sonar/modules/deposits/query.py
- sonar/modules/documents/query.py
- sonar/modules/documents/serializers/__init__.py
- sonar/modules/organisations/query.py
- sonar/modules/users/query.py
- tests/api/deposits/test_deposits_permissions.py
- tests/api/documents/test_documents_permissions.py
- tests/api/organisations/test_organisations_permissions.py
- tests/api/users/test_users_permissions.py
* Allows search for records when user is not logged and check permissions is disabled.
> search: fix query for resources

- sonar/translations/de/LC_MESSAGES/messages.po
- sonar/translations/en/LC_MESSAGES/messages.po
- sonar/translations/fr/LC_MESSAGES/messages.po
- sonar/translations/it/LC_MESSAGES/messages.po
- sonar/translations/messages.pot
* Synces translations with Transifex.
> translations: sync translations with Transifex

- README.rst
* Adds a weblate badge to the README file.
> documentation: add a weblate badge

- sonar/translations/de/LC_MESSAGES/messages.po
- sonar/translations/en/LC_MESSAGES/messages.po
- sonar/translations/fr/LC_MESSAGES/messages.po
- sonar/translations/it/LC_MESSAGES/messages.po
- sonar/translations/messages.pot
- sonar/translations/nb_NO/LC_MESSAGES/messages.po
* Updates translations catalogs for all languages.
> translations: update catalogs

- sonar/modules/users/utils.py
* Changes the label for welcome message subject.
* Closes #350.
> project: change welcome subject

- sonar/modules/deposits/mappings/v7/deposits/deposit-v1.0.0.json
- sonar/modules/documents/mappings/v7/documents/document-v1.0.0.json
- sonar/modules/organisations/mappings/v7/organisations/organisation-v1.0.0.json
- sonar/modules/users/mappings/v7/users/user-v1.0.0.json
* Sets number of shards to 8.
* Sets number of replicas to 2.
> mappings: set shards and replicas values

- sonar/modules/documents/minters.py
- sonar/theme/views.py
- tests/conftest.py
- tests/ui/test_api.py
- tests/ui/test_views.py
* Adds a view redirecting to the right documents when a RERODOC PID is given.
* Checks the identifier source for retrieving documents.
* Closes #411.
> documents: RERODOC permalink

- sonar/config.py
- sonar/theme/templates/sonar/page.html
* Adds a global Google analytics tracking code for the project.
* Closes #109.
> google analytics: add tracking code

- setup.py
- sonar/monitoring/__init__.py
- sonar/monitoring/api/data_integrity.py
- sonar/monitoring/api/database.py
- sonar/monitoring/views/__init__.py
- tests/api/monitoring/test_monitoring_views.py
- tests/unit/monitoring/test_api_data_integrity.py
- tests/unit/monitoring/test_api_db_connection.py
* Adds monitoring for DB connections and activities.
* Adds monitoring for data integrity between database and elasticsearch.
* Closes #448.
> monitoring: data integrity and DB connections

- sonar/theme/assets/scss/common/_theme.scss
- sonar/theme/templates/sonar/accounts/forgot_password.html
- sonar/theme/templates/sonar/accounts/login.html
- sonar/theme/templates/sonar/accounts/reset_password.html
- sonar/theme/templates/sonar/accounts/signup.html
- sonar/theme/templates/sonar/footer.html
- sonar/theme/templates/sonar/frontpage.html
- sonar/theme/templates/sonar/oauth/signup.html
- sonar/theme/templates/sonar/partial/navbar.html
* Improves the display in small screens.
* Changes the links and display for sign in and sign up actions.
* Changes occurrences `Log in` for `Sign in`.
* Updates the frontpage.
* Closes #365.
* Closes #474.
* Closes #476.
> design: improve responsive display

- sonar/modules/config.py
* Upgrades `sonar-ui` to version 1.0.1.
> dependencies: upgrade `sonar-ui`

- sonar/translations/de/LC_MESSAGES/messages.po
- sonar/translations/en/LC_MESSAGES/messages.po
- sonar/translations/fr/LC_MESSAGES/messages.po
- sonar/translations/it/LC_MESSAGES/messages.po
- sonar/translations/messages.pot
- sonar/translations/nb_NO/LC_MESSAGES/messages.po
English translated at 100.0% (960 of 960 strings)
French translated at 100.0% (960 of 960 strings)
Italian translated at 100.0% (960 of 960 strings)
German translated at 100.0% (960 of 960 strings)
Co-authored-by: Hosted Weblate <hosted@weblate.org>
Co-authored-by: Nicolas Prongué <n.prongue@outlook.com>
Co-authored-by: iGor milhit <igor.milhit@rero.ch>
Translate-URL: https://hosted.weblate.org/projects/rero_plus/sonar/
Translation: RERO+/sonar
> translations: update catalog

- sonar/theme/views.py
* Enables applications menu entry to allow user to generate an access token.
* Closes #415.
> user: enable applications menu entry

- sonar/theme/assets/scss/vge/theme.scss
- sonar/theme/webpack.py
Adds a custom them for VGE organisation.
> organisation: theme for VGE

- sonar/monitoring/api/data_integrity.py
- sonar/monitoring/views/__init__.py
- tests/api/monitoring/test_monitoring_views.py
- tests/unit/monitoring/test_api_data_integrity.py
* Improves monitoring API endpoints.
* Moves the authentication check to `before_request` hook.
* Adds an endpoint to get the ES health.
> monitoring: improve returned information

- poetry.lock
- pyproject.toml
- setup.py
- sonar/modules/babel_extractors.py
- sonar/modules/config.py
- sonar/theme/views.py
- sonar/translations/rest.py
- tests/api/translations/test_translations_rest.py
* Creates a REST endpoint to get translations for a given language.
* Closes #493.
> translations: create REST endpoint

- .gitignore
- scripts/bootstrap
- setup.py
- sonar/config_sonar.py
- sonar/dedicated/hepvs/projects/__init__.py
- sonar/dedicated/hepvs/projects/jsonschemas/__init__.py
- sonar/dedicated/hepvs/projects/jsonschemas/hepvs/projects/project-v1.0.0_src.json
- sonar/dedicated/hepvs/projects/schema.py
- sonar/modules/utils.py
- sonar/resources/projects/api.py
- sonar/resources/projects/jsonschemas/projects/project-v1.0.0_src.json
- sonar/resources/projects/service.py
- sonar/theme/views.py
- tests/ui/test_utils.py
- tests/unit/dedicated/hepvs/test_dedicated_projects_hepvs.py
* Creates a custom projects resource for HEP-VS.
* Adds an utility function to check if user's organisation has a custom resource.
* Enables datepickers for `startDate` and `endDate` fields.
> projects: create custom resource for HEP-VS

- poetry.lock
- scripts/bootstrap
* Removes fix done in #563.
* Update dependencies.
> assets: remove manifest fix

- sonar/json_schemas/json_schema_base.py
Forces to clear cache for JSON schemas, to have the right schema content.
> json schemas: force the cache to be cleared.

- sonar/theme/templates/sonar/accounts/profile.html
- sonar/theme/templates/sonar/manage.html
- sonar/theme/templates/sonar/search.html
* Updates scripts to load the UI because they are generated for ES5 and ES2015 now.
> ui: update scripts

- data/oai_sources.json
- sonar/modules/documents/dojson/rerodoc/model.py
- sonar/modules/documents/dojson/rerodoc/overdo.py
- tests/ui/documents/dojson/rerodoc/test_rerodoc_model.py
* Adds four new sources for OAI records harvesting for VGE from RERO DOC.
> vge: add sources for OAI harvesting from RERO DOC

- sonar/modules/documents/templates/documents/record.html
* Hides Dewey classification in documents detail views.
* Closes #550.
> documents: hide Dewey classification

- sonar/config.py
- sonar/templates/security/email/reset_instructions.txt
- sonar/templates/security/email/reset_notice.html
- sonar/templates/security/email/reset_notice.txt
* Updates password forgotten emails.
* Closes #343.
> accounts: password forgotten emails

- sonar/modules/documents/views.py
- tests/ui/documents/test_dc_schema.py
- tests/ui/documents/test_documents_views.py
* Displays the issue and pages even if volume is not set.
* Closes #370.
> documents: fix `partOf` format

- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/mappings/v7/documents/document-v1.0.0.json
* Adds suggestions for contributor agent preferred name.
* Closes #542.
> contributors: add suggestions for name

- docker-compose.full.yml
- docker-services.yml
> docker: change always to unless-stopped on restart parameter

- sonar/modules/organisations/serializers/schemas/export.py
> organisations: fix export serialization

- sonar/config.py
- sonar/es_templates/v7/record.json
- sonar/modules/collections/mappings/v7/collections/collection-v1.0.0.json
- sonar/modules/documents/mappings/v7/documents/document-v1.0.0.json
- sonar/modules/organisations/mappings/v7/organisations/organisation-v1.0.0.json
- sonar/modules/subdivisions/mappings/v7/subdivisions/subdivision-v1.0.0.json
- sonar/modules/users/mappings/v7/users/user-v1.0.0.json
- sonar/resources/projects/mappings/v7/projects/project-v1.0.0.json
- sonar/resources/projects/service.py
- sonar/theme/templates/sonar/macros/menu.html
- sonar/theme/templates/sonar/page.html
- sonar/theme/templates/sonar/partial/navbar.html
- sonar/theme/templates/sonar/partial/switch_aai_dropdown.html
* Configures sorting behavior for all records types.
* Indexes the fields to sort on as keyword.
* Closes #402.
> records: configure sorting behavior

- sonar/modules/cli/imports.py
- Improves #620 
- What command should I have to run to test your PR? `invenio imports hepbejune /[FOLDER]/export_memoires_curated_20210913_sample.csv [FOLDER]`
- What should I test through the UI? The records are imported with the correct fields
> documents: adapt import from HEP BEJUNE

- sonar/theme/templates/sonar/page.html
* Closes #667.
- In mobile, the main menu button is inactive.
- Check hamburger menu
> application: fix responsive design menu

- sonar/json_schemas/deposits_json_schema.py
- sonar/modules/collections/permissions.py
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
- tests/api/collections/test_collections_permissions.py
- tests/conftest.py
- tests/ui/deposits/test_deposits_api.py
- tests/ui/test_views.py
* Fixes deposit creation with a submitter without a main file.
* Allows to get the deposit JSONSchema as anonymous user.
* Fixes the collection permissions.
* Removes the collection creation from the deposit form.
* Closes rero#683.
Co-Authored-by:Johnny Mariéthoz <johnny.mariethoz@rero.ch>
> collections: allow submitter to search in collections.

- sonar/dedicated/hepvs/projects/jsonschemas/hepvs/projects/project-v1.0.0_src.json
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
* Fixes the form validation error during a document edition by an
administrator.
* Closes #689.
* Be sure that the `model` is defined in `hideExpression` and
`templateOptions.require`.
Co-Authored-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>
> documents: fix document edition

- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
> deposits: change title and add description on publisher field

- sonar/modules/documents/dojson/rerodoc/model.py
- it improves the import of RERO DOC records for ROAR, by making the distinction between 'mémoire de master' and 'mémoire de master spécialisé' 
> documents: improve custom field import from RERO DOC for ROAR

- sonar/modules/documents/dojson/rerodoc/model.py
* Imports the "faculty" and "department" fields from RERO DOC
to "customField1" and "customField2", resp. Applies only to FOLIA.
* Closes #691.
> documents: import faculty and department from RERO DOC for UNIFR

- sonar/modules/documents/dojson/sru/model.py
- tests/api/swisscovery/test_swisscovery_rest.py
If field 502 is available in the record, it is
analyzed to determine the type of document.
> deposit: improve document type detection.

- sonar/theme/assets/scss/hepbejune/_variables.scss
- sonar/theme/assets/scss/usi/_variables.scss
> Change color scheme for two dedicated repositories (tentative)

- CHANGELOG.md
- poetry.lock
- pyproject.toml
- sonar/config_sonar.py
- sonar/version.py
* Upgrades sonar-ui to version 1.4.0.
* Forces dependency jedi to be < 0.18.0 to avoid `invenio shell` crash.
> release: v1.4.0

- CHANGELOG.md
- pyproject.toml
- scripts/test
- sonar/config_sonar.py
- sonar/version.py
* Upgrades sonar-ui to version 1.4.1.
* Adds security exceptions.
> release: v1.4.1

- scripts/test
> dependencies: add ignores on safety check

- CHANGELOG.md
- pyproject.toml
- sonar/version.py
> release: v1.4.2

- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
* Fixes the control of the availability of information on hidExpression.
* Updates the contribution field.
* Closes rero#728.
* Closes rero#739.
* Closes rero#740.
- sonar-ui: https://github.com/rero/sonar-ui/pull/285
- To fix the problems on the editor
- Test all elements on document editor.
- Test all elements on deposit editor.
> editor: adjust some elements on document jsonschema

- SECURITY.rst
> security: Add config:

- poetry.lock
- pyproject.toml
- scripts/test
* Uses invenio-oaiserver: https://github.com/rero/invenio-oaiserver/tree/sets.
* Changes tests to exit for errors for each test.
> oaiserver: fix sets

- scripts/test
- sonar/ext.py
> safety: Add pillow exclusions

- poetry.lock
- pyproject.toml
> document: fix file preview.

- CHANGELOG.md
- pyproject.toml
- sonar/config_sonar.py
- sonar/modules/organisations/api.py
- sonar/version.py
> release: v1.5.0

- CHANGELOG.md
- pyproject.toml
- sonar/version.py
> release: v1.5.1

- data/organisations/data.json
- data/users/data.json
- sonar/json_schemas/deposits_json_schema.py
- sonar/json_schemas/documents_json_schema.py
- sonar/json_schemas/factory.py
- sonar/json_schemas/organisations_json_schema.py
- sonar/json_schemas/projects_json_schema.py
- sonar/json_schemas/users_json_schema.py
- sonar/theme/views.py
- tests/conftest.py
- tests/ui/test_views.py
* Moves the schema processing to dedicated classes.
* Adds fixtures for organisations and users.
* Removes collections, subdivisions, customField1, customField2
and customField3 on documents and deposits schema.
* Removes subdivison on users for shared organisation.
* Closes https://github.com/rero/sonar/issues/752.
> schemas: remove fields on documents, deposits and users

- sonar/theme/templates/sonar/macros/macro.html
> documents: hide label file in the detailed view

- poetry.lock
* Updates invenio-account to version 1.4.11.
* Closes #776.
DE: Passwort zurücksetzen
EN: Reset password
FR: Réinitialiser le mot de passe
IT: Reimposta la password
> translation: reset password translation fix

- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/templates/documents/record.html
- sonar/modules/documents/views.py
* Renames the title of the partof field with "Contained in or submitted to
(journal, book, proceedings)".
* Changes the title field on detailed view with "Submitted to" for preprint.
* Closes #722.
> documents: label change for preprint

- sonar/config.py
> oai-pmh: configure admin email

- CHANGELOG.md
> documentation: fix v1.6.0 changelog

- poetry.lock
- pyproject.toml
* Updates package dependencies.
> dependencies: update

- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/templates/documents/record.html
- sonar/modules/documents/views.py
- sonar/theme/templates/sonar/macros/macro.html
- tests/api/documents/test_documents_permissions.py
- tests/ui/documents/test_dc_schema.py
- tests/ui/documents/test_documents_views.py
* Adds fields: notes, contentNote, editionStatement, series,
additionalMaterials, otherMaterialCharacteristics, oa_status.
* Splits the data in the contributions field (meeting and other).
* Improves formatting on the partOf field.
* Closes https://github.com/rero/sonar/issues/723.
Sonar ui: https://github.com/rero/sonar-ui/pull/303
> documents: add and improve fields on detailed view

- sonar/modules/utils.py
> utils: add missing import for abort

- .github_changelog_generator
- add task label to ignore list
> documentation: update changelog parameters

- Dockerfile.base
> pdf-extractor: fix thumbnails creation

- .github/workflows/continuous-integration-test.yml
- poetry.lock
- pyproject.toml
- pytest.ini
- scripts/bootstrap
- scripts/server
- sonar/modules/deposits/rest.py
- sonar/modules/documents/rest.py
- sonar/modules/pdf_extractor/views/api.py
- sonar/modules/swisscovery/rest.py
- sonar/monitoring/views/__init__.py
- sonar/suggestions/rest.py
- sonar/translations/rest.py
* Adds support for poetry > 1.0.10.
> deployment: update poetry

- docker-services.yml
> pdf-extractor: update grobit

- sonar/modules/utils.py
* Changes import of abort to use the flask function.
* Fixes Sentry SONAR-F2.
> utils: fix abort import

- Dockerfile.base
> deployment: fix bootstrap --deploy

- poetry.lock
- pyproject.toml
> dependencies: remove invenio-circulation

- sonar/modules/documents/serializers/dc.py
- sonar/modules/documents/serializers/schemas/dc.py
- tests/ui/documents/test_dc_schema.py
* Adds files into the `dc:identifier`.
* Adds attributes `xml:lang` on the descriptions, subjects
and titles fields.
* Closes #661.
* Closes #800.
> document: dublin core improvements

- CHANGELOG.md
- pyproject.toml
- sonar/config_sonar.py
- sonar/version.py
> release: v1.7.0

- sonar/modules/deposits/api.py
- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
- sonar/modules/deposits/mappings/v7/deposits/deposit-v1.0.0.json
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/mappings/v7/documents/document-v1.0.0.json
- sonar/modules/documents/marshmallow/json.py
- sonar/modules/documents/serializers/schemas/dc.py
- sonar/modules/documents/templates/documents/_other_edition.html
- sonar/modules/documents/templates/documents/record.html
- tests/conftest.py
- tests/ui/deposits/test_deposits_api.py
- tests/ui/documents/test_dc_schema.py
* Adds relatedTo field on the document and the deposit resource.
* Updates Dublin Core to export the new relatedTo field
into the relations.
* Updates of the creation of the document from the deposit for
the new relatedTo field.
* Closes #544.
⚠️  ES update mapping
> document, deposit: add relatedTo field

- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/documents/templates/documents/record.html
* Removes show more on abstract on the detail view.
* Changes the field type to textarea for the abtract field in
the form.
> document: update of the abstract display

- poetry.lock
- pyproject.toml
- sonar/config_sonar.py
- sonar/modules/documents/api.py
- sonar/modules/documents/dnb.py
- sonar/modules/documents/extensions.py
- sonar/modules/documents/tasks.py
- sonar/modules/documents/urn.py
- tests/api/conftest.py
- tests/api/documents/test_dnb_api.py
- tests/conftest.py
- tests/ui/documents/test_document_urn.py
Co-Authored-by: Aly Badr <aly.badr@rero.ch>
> urn: register and verify at DNB

- sonar/config_sonar.py
- sonar/modules/documents/cli/urn.py
- sonar/modules/documents/urn.py
* Adds a cli to add urn code loaded documents.
Co-Authored-by: Aly Badr <aly.badr@rero.ch>
> document: add urn for loaded documents

- sonar/theme/templates/sonar/footer.html
> templates: update footer info

- sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
> deposit editor: small display improvements

- sonar/resources/projects/serializers/csv.py
* Removes key translation in CSV serializer to prevent test failure.
> tests: fix csv serializer test

- sonar/theme/templates/sonar/macros/macro.html
- sonar/theme/templates/sonar/page_wiki.html
* Fixes flash messages not showing on wiki page.
* Fixes stats tooltip formulation and translation in public view.
> templates: fix display problems

- poetry.lock
- pyproject.toml
* Fixes dependencies-linked errors.
> flask-wiki: update to 0.2.2

- sonar/theme/views.py
- tests/ui/test_views.py
> logged user: fix settings

- CHANGELOG.md
- pyproject.toml
- sonar/version.py
> release: v1.8.1

- CHANGELOG.md
- pyproject.toml
- sonar/version.py
> release: v1.8.2

- sonar/config_sonar.py
- sonar/modules/documents/cli/urn.py
- sonar/modules/documents/templates/documents/emailSNL.txt
- sonar/snl/__init__.py
- sonar/snl/ftp/__init__.py
- tests/unit/documents/urn/test_urn_cli.py
- tests/unit/snl/ftp/test_snl_repository.py
* upload files to the server
* list all files on the server
* replace pdf file in record
US: https://github.com/rero/sonar/issues/849
> urn: cli to connect to the SNL server via FTP

- poetry.lock
- scripts/test
> dependencies: fix vulnerabilities

- sonar/common/jsonschemas/oa-status-v1.0.0.json
> documents and deposits: add diamond oa status

- CHANGELOG.md
- pyproject.toml
- sonar/config_sonar.py
- sonar/version.py
> release: v1.9.0

- CHANGELOG.md
- pyproject.toml
- sonar/version.py
> release: v1.9.1

- scripts/functions
- scripts/setup
- sonar/config.py
- sonar/modules/cli/utils.py
- sonar/modules/permissions.py
- sonar/monitoring/views/__init__.py
- tests/ui/test_cli.py
* Add monitoring user and access token for setup.
> monitoring: access token

- poetry.lock
> dependencies: fix security issues for uwsgi

- Dockerfile.base
- scripts/test
- sonar/modules/documents/jsonschemas/documents/document-v1.0.0_src.json
- sonar/modules/organisations/jsonschemas/organisations/organisation-v1.0.0_src.json
- sonar/modules/users/jsonschemas/users/user-v1.0.0.json
- sonar/resources/projects/jsonschemas/projects/project-v1.0.0_src.json
* Fixes lxml conflict with uwsgi command for the deployment.
* Adds safety exceptions.
> deployment: fix docker file

- Dockerfile
- Dockerfile.base
- poetry.lock
- pyproject.toml
- sonar/config.py
* Uses bookworm for deployment.
* Disables uwsgi xml support.
> fix(deployment): fix lxml conflict packages

- sonar/modules/documents/jsonschemas/documents/document-v1.0.0.json
* Fixes the autocomplete configuration for the preferred_name field of contributions.
> fix(document): incorrect autocomplete config

- docker/nginx/nginx.conf
- scripts/test
* Adds types config for nginx.
> chore: update nginx config on docker

- sonar/modules/documents/templates/documents/record.html
> feat(document): add latex transformation

- .gitignore
- sonar/ext.py
- sonar/filters.py
- sonar/modules/collections/templates/collections/item.html
- sonar/modules/documents/templates/documents/record.html
If the organization is dedicated, the viewcode corresponds to its code.
* Closes #713.
> fix(document): fix viewcode on collection
